package jiradata

/////////////////////////////////////////////////////////////////////////
// This Code is Generated by SlipScheme Project:
// https://github.com/coryb/slipscheme
//
// Generated with command:
// slipscheme -pkg jiradata -overwrite ../schemas/SearchResults.json
/////////////////////////////////////////////////////////////////////////
//                            DO NOT EDIT                              //
/////////////////////////////////////////////////////////////////////////

// FieldMeta defined from schema:
// {
//   "title": "Field Meta",
//   "type": "object",
//   "properties": {
//     "allowedValues": {
//       "type": "array",
//       "items": {}
//     },
//     "autoCompleteUrl": {
//       "type": "string"
//     },
//     "hasDefaultValue": {
//       "type": "boolean"
//     },
//     "key": {
//       "type": "string"
//     },
//     "name": {
//       "type": "string"
//     },
//     "operations": {
//       "type": "array",
//       "items": {
//         "type": "string"
//       }
//     },
//     "required": {
//       "type": "boolean"
//     },
//     "schema": {
//       "$ref": "#/definitions/json-type"
//     }
//   }
// }
type FieldMeta struct {
	AllowedValues   []interface{} `json:"allowedValues,omitempty" yaml:"allowedValues,omitempty"`
	AutoCompleteURL string        `json:"autoCompleteUrl,omitempty" yaml:"autoCompleteUrl,omitempty"`
	HasDefaultValue bool          `json:"hasDefaultValue,omitempty" yaml:"hasDefaultValue,omitempty"`
	Key             string        `json:"key,omitempty" yaml:"key,omitempty"`
	Name            string        `json:"name,omitempty" yaml:"name,omitempty"`
	Operations      []string      `json:"operations,omitempty" yaml:"operations,omitempty"`
	Required        bool          `json:"required,omitempty" yaml:"required,omitempty"`
	Schema          interface{}   `json:"schema,omitempty" yaml:"schema,omitempty"`
}
