package jiradata

/////////////////////////////////////////////////////////////////////////
// This Code is Generated by SlipScheme Project:
// https://github.com/coryb/slipscheme
//
// Generated with command: slipscheme -pkg jiradata -overwrite ../schemas/TransitionsMeta.json
/////////////////////////////////////////////////////////////////////////
//                            DO NOT EDIT                              //
/////////////////////////////////////////////////////////////////////////

type JsonType struct {
	Custom   string `json:"custom,omitempty" yaml:"custom,omitempty"`
	CustomID int    `json:"customId,omitempty" yaml:"customId,omitempty"`
	Items    string `json:"items,omitempty" yaml:"items,omitempty"`
	System   string `json:"system,omitempty" yaml:"system,omitempty"`
	Type     string `json:"type,omitempty" yaml:"type,omitempty"`
}
