package jiradata

/////////////////////////////////////////////////////////////////////////
// This Code is Generated by SlipScheme Project:
// https://github.com/coryb/slipscheme
//
// Generated with command:
// slipscheme -pkg jiradata -overwrite ../schemas/SearchResults.json
/////////////////////////////////////////////////////////////////////////
//                            DO NOT EDIT                              //
/////////////////////////////////////////////////////////////////////////

// Properties defined from schema:
// {
//   "title": "Properties",
//   "type": "object",
//   "properties": {
//     "properties": {
//       "title": "properties",
//       "type": "object",
//       "patternProperties": {
//         ".+": {
//           "type": "string"
//         }
//       }
//     }
//   }
// }
type Properties struct {
	Properties map[string]string `json:"properties,omitempty" yaml:"properties,omitempty"`
}
