package jiradata

/////////////////////////////////////////////////////////////////////////
// This Code is Generated by SlipScheme Project:
// https://github.com/coryb/slipscheme
//
// Generated with command:
// slipscheme -pkg jiradata -overwrite ../schemas/SearchRequest.json
/////////////////////////////////////////////////////////////////////////
//                            DO NOT EDIT                              //
/////////////////////////////////////////////////////////////////////////

// SearchRequest defined from schema:
// {
//   "title": "Search Request",
//   "id": "https://docs.atlassian.com/jira/REST/schema/search-request#",
//   "type": "object",
//   "properties": {
//     "fields": {
//       "title": "fields",
//       "type": "array",
//       "items": {
//         "type": "string"
//       }
//     },
//     "fieldsByKeys": {
//       "title": "fieldsByKeys",
//       "type": "boolean"
//     },
//     "jql": {
//       "title": "jql",
//       "type": "string"
//     },
//     "maxResults": {
//       "title": "maxResults",
//       "type": "integer"
//     },
//     "startAt": {
//       "title": "startAt",
//       "type": "integer"
//     },
//     "validateQuery": {
//       "title": "validateQuery",
//       "type": "boolean"
//     }
//   }
// }
type SearchRequest struct {
	Fields        Fields `json:"fields,omitempty" yaml:"fields,omitempty"`
	FieldsByKeys  bool   `json:"fieldsByKeys,omitempty" yaml:"fieldsByKeys,omitempty"`
	JQL           string `json:"jql,omitempty" yaml:"jql,omitempty"`
	MaxResults    int    `json:"maxResults,omitempty" yaml:"maxResults,omitempty"`
	StartAt       int    `json:"startAt,omitempty" yaml:"startAt,omitempty"`
	ValidateQuery bool   `json:"validateQuery,omitempty" yaml:"validateQuery,omitempty"`
}
