package jiradata

/////////////////////////////////////////////////////////////////////////
// This Code is Generated by SlipScheme Project:
// https://github.com/coryb/slipscheme
//
// Generated with command: slipscheme -pkg jiradata -overwrite ../schemas/TransitionsMeta.json
/////////////////////////////////////////////////////////////////////////
//                            DO NOT EDIT                              //
/////////////////////////////////////////////////////////////////////////

type StatusCategory struct {
	ColorName string `json:"colorName,omitempty" yaml:"colorName,omitempty"`
	ID        int    `json:"id,omitempty" yaml:"id,omitempty"`
	Key       string `json:"key,omitempty" yaml:"key,omitempty"`
	Name      string `json:"name,omitempty" yaml:"name,omitempty"`
	Self      string `json:"self,omitempty" yaml:"self,omitempty"`
}
