package jiradata

/////////////////////////////////////////////////////////////////////////
// This Code is Generated by SlipScheme Project:
// https://github.com/coryb/slipscheme
//
// Generated with command: slipscheme -pkg jiradata -overwrite ../schemas/TransitionsMeta.json
/////////////////////////////////////////////////////////////////////////
//                            DO NOT EDIT                              //
/////////////////////////////////////////////////////////////////////////

type Transition struct {
	Expand    string       `json:"expand,omitempty" yaml:"expand,omitempty"`
	Fields    FieldMetaMap `json:"fields,omitempty" yaml:"fields,omitempty"`
	HasScreen bool         `json:"hasScreen,omitempty" yaml:"hasScreen,omitempty"`
	ID        string       `json:"id,omitempty" yaml:"id,omitempty"`
	Name      string       `json:"name,omitempty" yaml:"name,omitempty"`
	To        *Status      `json:"to,omitempty" yaml:"to,omitempty"`
}
