package jiradata

/////////////////////////////////////////////////////////////////////////
// This Code is Generated by SlipScheme Project:
// https://github.com/coryb/slipscheme
//
// Generated with command: slipscheme -pkg jiradata -overwrite ../schemas/TransitionsMeta.json
/////////////////////////////////////////////////////////////////////////
//                            DO NOT EDIT                              //
/////////////////////////////////////////////////////////////////////////

type TransitionsMeta struct {
	Expand      string      `json:"expand,omitempty" yaml:"expand,omitempty"`
	Transitions Transitions `json:"transitions,omitempty" yaml:"transitions,omitempty"`
}
