package jiradata

/////////////////////////////////////////////////////////////////////////
// This Code is Generated by SlipScheme Project:
// https://github.com/coryb/slipscheme
//
// Generated with command:
// slipscheme -dir jiradata -pkg jiradata -overwrite schemas/AuthSuccess.json
/////////////////////////////////////////////////////////////////////////
//                            DO NOT EDIT                              //
/////////////////////////////////////////////////////////////////////////

// AuthSuccess defined from schema:
// {
//   "title": "Auth Success",
//   "id": "https://docs.atlassian.com/jira/REST/schema/auth-success#",
//   "type": "object",
//   "properties": {
//     "loginInfo": {
//       "title": "Login Info",
//       "type": "object",
//       "properties": {
//         "failedLoginCount": {
//           "title": "failedLoginCount",
//           "type": "integer"
//         },
//         "lastFailedLoginTime": {
//           "title": "lastFailedLoginTime",
//           "type": "string"
//         },
//         "loginCount": {
//           "title": "loginCount",
//           "type": "integer"
//         },
//         "previousLoginTime": {
//           "title": "previousLoginTime",
//           "type": "string"
//         }
//       }
//     },
//     "session": {
//       "title": "Session Info",
//       "type": "object",
//       "properties": {
//         "name": {
//           "title": "name",
//           "type": "string"
//         },
//         "value": {
//           "title": "value",
//           "type": "string"
//         }
//       }
//     }
//   }
// }
type AuthSuccess struct {
	LoginInfo *LoginInfo   `json:"loginInfo,omitempty" yaml:"loginInfo,omitempty"`
	Session   *SessionInfo `json:"session,omitempty" yaml:"session,omitempty"`
}
