package jiradata

/////////////////////////////////////////////////////////////////////////
// This Code is Generated by SlipScheme Project:
// https://github.com/coryb/slipscheme
//
// Generated with command:
// slipscheme -dir jiradata -pkg jiradata -overwrite schemas/LinkIssueRequest.json
/////////////////////////////////////////////////////////////////////////
//                            DO NOT EDIT                              //
/////////////////////////////////////////////////////////////////////////

// Comment defined from schema:
// {
//   "title": "Comment",
//   "type": "object",
//   "properties": {
//     "author": {
//       "title": "User",
//       "type": "object",
//       "properties": {
//         "accountId": {
//           "type": "string"
//         },
//         "active": {
//           "type": "boolean"
//         },
//         "avatarUrls": {
//           "type": "object",
//           "patternProperties": {
//             ".+": {
//               "type": "string"
//             }
//           }
//         },
//         "displayName": {
//           "type": "string"
//         },
//         "emailAddress": {
//           "type": "string"
//         },
//         "key": {
//           "type": "string"
//         },
//         "name": {
//           "type": "string"
//         },
//         "timeZone": {
//           "type": "string"
//         }
//       }
//     },
//     "body": {
//       "title": "body",
//       "type": "string"
//     },
//     "created": {
//       "title": "created",
//       "type": "string"
//     },
//     "id": {
//       "title": "id",
//       "type": "string"
//     },
//     "properties": {
//       "title": "properties",
//       "type": "array",
//       "items": {
//         "title": "Entity Property",
//         "type": "object",
//         "properties": {
//           "key": {
//             "title": "key",
//             "type": "string"
//           },
//           "value": {
//             "title": "value"
//           }
//         }
//       }
//     },
//     "renderedBody": {
//       "title": "renderedBody",
//       "type": "string"
//     },
//     "updateAuthor": {
//       "title": "User",
//       "type": "object",
//       "properties": {
//         "accountId": {
//           "type": "string"
//         },
//         "active": {
//           "type": "boolean"
//         },
//         "avatarUrls": {
//           "type": "object",
//           "patternProperties": {
//             ".+": {
//               "type": "string"
//             }
//           }
//         },
//         "displayName": {
//           "type": "string"
//         },
//         "emailAddress": {
//           "type": "string"
//         },
//         "key": {
//           "type": "string"
//         },
//         "name": {
//           "type": "string"
//         },
//         "timeZone": {
//           "type": "string"
//         }
//       }
//     },
//     "updated": {
//       "title": "updated",
//       "type": "string"
//     },
//     "visibility": {
//       "title": "Visibility",
//       "type": "object",
//       "properties": {
//         "type": {
//           "title": "type",
//           "type": "string"
//         },
//         "value": {
//           "title": "value",
//           "type": "string"
//         }
//       }
//     }
//   }
// }
type Comment struct {
	Author       *User       `json:"author,omitempty" yaml:"author,omitempty"`
	Body         string      `json:"body,omitempty" yaml:"body,omitempty"`
	Created      string      `json:"created,omitempty" yaml:"created,omitempty"`
	ID           string      `json:"id,omitempty" yaml:"id,omitempty"`
	Properties   Properties  `json:"properties,omitempty" yaml:"properties,omitempty"`
	RenderedBody string      `json:"renderedBody,omitempty" yaml:"renderedBody,omitempty"`
	UpdateAuthor *User       `json:"updateAuthor,omitempty" yaml:"updateAuthor,omitempty"`
	Updated      string      `json:"updated,omitempty" yaml:"updated,omitempty"`
	Visibility   *Visibility `json:"visibility,omitempty" yaml:"visibility,omitempty"`
}
