package jiradata

/////////////////////////////////////////////////////////////////////////
// This Code is Generated by SlipScheme Project:
// https://github.com/coryb/slipscheme
//
// Generated with command:
// slipscheme -dir jiradata -pkg jiradata -overwrite schemas/CurrentUser.json
/////////////////////////////////////////////////////////////////////////
//                            DO NOT EDIT                              //
/////////////////////////////////////////////////////////////////////////

// CurrentUser defined from schema:
// {
//   "title": "Current User",
//   "id": "https://docs.atlassian.com/jira/REST/schema/current-user#",
//   "type": "object",
//   "properties": {
//     "loginInfo": {
//       "title": "Login Info",
//       "type": "object",
//       "properties": {
//         "failedLoginCount": {
//           "title": "failedLoginCount",
//           "type": "integer"
//         },
//         "lastFailedLoginTime": {
//           "title": "lastFailedLoginTime",
//           "type": "string"
//         },
//         "loginCount": {
//           "title": "loginCount",
//           "type": "integer"
//         },
//         "previousLoginTime": {
//           "title": "previousLoginTime",
//           "type": "string"
//         }
//       }
//     },
//     "name": {
//       "title": "name",
//       "type": "string"
//     },
//     "self": {
//       "title": "self",
//       "type": "string"
//     }
//   }
// }
type CurrentUser struct {
	LoginInfo *LoginInfo `json:"loginInfo,omitempty" yaml:"loginInfo,omitempty"`
	Name      string     `json:"name,omitempty" yaml:"name,omitempty"`
	Self      string     `json:"self,omitempty" yaml:"self,omitempty"`
}
