package jiradata

/////////////////////////////////////////////////////////////////////////
// This Code is Generated by SlipScheme Project:
// https://github.com/coryb/slipscheme
//
// Generated with command:
// slipscheme -dir jiradata -pkg jiradata -overwrite schemas/SearchResults.json
/////////////////////////////////////////////////////////////////////////
//                            DO NOT EDIT                              //
/////////////////////////////////////////////////////////////////////////

// EditMeta defined from schema:
// {
//   "title": "Edit Meta",
//   "type": "object",
//   "properties": {
//     "fields": {
//       "title": "fields",
//       "type": "object",
//       "patternProperties": {
//         ".+": {
//           "title": "Field Meta",
//           "type": "object",
//           "properties": {
//             "allowedValues": {
//               "type": "array",
//               "items": {}
//             },
//             "autoCompleteUrl": {
//               "type": "string"
//             },
//             "defaultValue": {},
//             "hasDefaultValue": {
//               "type": "boolean"
//             },
//             "key": {
//               "type": "string"
//             },
//             "name": {
//               "type": "string"
//             },
//             "operations": {
//               "type": "array",
//               "items": {
//                 "type": "string"
//               }
//             },
//             "required": {
//               "type": "boolean"
//             },
//             "schema": {
//               "$ref": "#/definitions/json-type"
//             }
//           }
//         }
//       }
//     }
//   }
// }
type EditMeta struct {
	Fields FieldMetaMap `json:"fields,omitempty" yaml:"fields,omitempty"`
}
