package jiradata

/////////////////////////////////////////////////////////////////////////
// This Code is Generated by SlipScheme Project:
// https://github.com/coryb/slipscheme
//
// Generated with command:
// slipscheme -dir jiradata -pkg jiradata -overwrite schemas/ErrorCollection.json
/////////////////////////////////////////////////////////////////////////
//                            DO NOT EDIT                              //
/////////////////////////////////////////////////////////////////////////

// ErrorCollection defined from schema:
// {
//   "title": "Error Collection",
//   "id": "https://docs.atlassian.com/jira/REST/schema/error-collection#",
//   "type": "object",
//   "properties": {
//     "errorMessages": {
//       "title": "errorMessages",
//       "type": "array",
//       "items": {
//         "type": "string"
//       }
//     },
//     "errors": {
//       "title": "errors",
//       "type": "object",
//       "patternProperties": {
//         ".+": {
//           "type": "string"
//         }
//       }
//     },
//     "status": {
//       "title": "status",
//       "type": "integer"
//     }
//   }
// }
type ErrorCollection struct {
	ErrorMessages ErrorMessages     `json:"errorMessages,omitempty" yaml:"errorMessages,omitempty"`
	Errors        map[string]string `json:"errors,omitempty" yaml:"errors,omitempty"`
	Status        int               `json:"status,omitempty" yaml:"status,omitempty"`
}
