package jiradata

/////////////////////////////////////////////////////////////////////////
// This Code is Generated by SlipScheme Project:
// https://github.com/coryb/slipscheme
//
// Generated with command:
// slipscheme -dir jiradata -pkg jiradata -overwrite schemas/IssueUpdate.json
/////////////////////////////////////////////////////////////////////////
//                            DO NOT EDIT                              //
/////////////////////////////////////////////////////////////////////////

// FieldOperationsMap defined from schema:
// {
//   "title": "update",
//   "type": "object",
//   "patternProperties": {
//     ".+": {
//       "type": "array",
//       "items": {
//         "title": "Field Operation",
//         "type": "object"
//       }
//     }
//   }
// }
type FieldOperationsMap map[string]FieldOperations
