package jiradata

/////////////////////////////////////////////////////////////////////////
// This Code is Generated by SlipScheme Project:
// https://github.com/coryb/slipscheme
//
// Generated with command:
// slipscheme -pkg jiradata -dir jiradata -overwrite schemas/IssueUpdate.json
/////////////////////////////////////////////////////////////////////////
//                            DO NOT EDIT                              //
/////////////////////////////////////////////////////////////////////////

// FieldOperation defined from schema:
// {
//   "title": "Field Operation",
//   "type": "object"
// }
type FieldOperation map[string]interface{}
