package jiradata

/////////////////////////////////////////////////////////////////////////
// This Code is Generated by SlipScheme Project:
// https://github.com/coryb/slipscheme
//
// Generated with command:
// slipscheme -dir jiradata -pkg jiradata -overwrite schemas/TransitionsMeta.json
/////////////////////////////////////////////////////////////////////////
//                            DO NOT EDIT                              //
/////////////////////////////////////////////////////////////////////////

// FieldMetaMap defined from schema:
// {
//   "title": "fields",
//   "type": "object",
//   "patternProperties": {
//     ".+": {
//       "title": "Field Meta",
//       "type": "object",
//       "properties": {
//         "allowedValues": {
//           "title": "allowedValues",
//           "type": "array",
//           "items": {}
//         },
//         "autoCompleteUrl": {
//           "title": "autoCompleteUrl",
//           "type": "string"
//         },
//         "defaultValue": {
//           "title": "defaultValue"
//         },
//         "hasDefaultValue": {
//           "title": "hasDefaultValue",
//           "type": "boolean"
//         },
//         "key": {
//           "title": "key",
//           "type": "string"
//         },
//         "name": {
//           "title": "name",
//           "type": "string"
//         },
//         "operations": {
//           "title": "operations",
//           "type": "array",
//           "items": {
//             "type": "string"
//           }
//         },
//         "required": {
//           "title": "required",
//           "type": "boolean"
//         },
//         "schema": {
//           "title": "Json Type",
//           "type": "object",
//           "properties": {
//             "custom": {
//               "title": "custom",
//               "type": "string"
//             },
//             "customId": {
//               "title": "customId",
//               "type": "integer"
//             },
//             "items": {
//               "title": "items",
//               "type": "string"
//             },
//             "system": {
//               "title": "system",
//               "type": "string"
//             },
//             "type": {
//               "title": "type",
//               "type": "string"
//             }
//           }
//         }
//       }
//     }
//   }
// }
type FieldMetaMap map[string]*FieldMeta
