package jiradata

/////////////////////////////////////////////////////////////////////////
// This Code is Generated by SlipScheme Project:
// https://github.com/coryb/slipscheme
//
// Generated with command:
// slipscheme -dir jiradata -pkg jiradata -overwrite schemas/TransitionsMeta.json
/////////////////////////////////////////////////////////////////////////
//                            DO NOT EDIT                              //
/////////////////////////////////////////////////////////////////////////

// FieldMeta defined from schema:
// {
//   "title": "Field Meta",
//   "type": "object",
//   "properties": {
//     "allowedValues": {
//       "title": "allowedValues",
//       "type": "array",
//       "items": {}
//     },
//     "autoCompleteUrl": {
//       "title": "autoCompleteUrl",
//       "type": "string"
//     },
//     "defaultValue": {
//       "title": "defaultValue"
//     },
//     "hasDefaultValue": {
//       "title": "hasDefaultValue",
//       "type": "boolean"
//     },
//     "key": {
//       "title": "key",
//       "type": "string"
//     },
//     "name": {
//       "title": "name",
//       "type": "string"
//     },
//     "operations": {
//       "title": "operations",
//       "type": "array",
//       "items": {
//         "type": "string"
//       }
//     },
//     "required": {
//       "title": "required",
//       "type": "boolean"
//     },
//     "schema": {
//       "title": "Json Type",
//       "type": "object",
//       "properties": {
//         "custom": {
//           "title": "custom",
//           "type": "string"
//         },
//         "customId": {
//           "title": "customId",
//           "type": "integer"
//         },
//         "items": {
//           "title": "items",
//           "type": "string"
//         },
//         "system": {
//           "title": "system",
//           "type": "string"
//         },
//         "type": {
//           "title": "type",
//           "type": "string"
//         }
//       }
//     }
//   }
// }
type FieldMeta struct {
	AllowedValues   AllowedValues `json:"allowedValues,omitempty" yaml:"allowedValues,omitempty"`
	AutoCompleteURL string        `json:"autoCompleteUrl,omitempty" yaml:"autoCompleteUrl,omitempty"`
	DefaultValue    interface{}   `json:"defaultValue,omitempty" yaml:"defaultValue,omitempty"`
	HasDefaultValue bool          `json:"hasDefaultValue,omitempty" yaml:"hasDefaultValue,omitempty"`
	Key             string        `json:"key,omitempty" yaml:"key,omitempty"`
	Name            string        `json:"name,omitempty" yaml:"name,omitempty"`
	Operations      Operations    `json:"operations,omitempty" yaml:"operations,omitempty"`
	Required        bool          `json:"required,omitempty" yaml:"required,omitempty"`
	Schema          *JSONType     `json:"schema,omitempty" yaml:"schema,omitempty"`
}
