package jiradata

/////////////////////////////////////////////////////////////////////////
// This Code is Generated by SlipScheme Project:
// https://github.com/coryb/slipscheme
//
// Generated with command:
// slipscheme -dir jiradata -pkg jiradata -overwrite schemas/ListofAttachment.json
/////////////////////////////////////////////////////////////////////////
//                            DO NOT EDIT                              //
/////////////////////////////////////////////////////////////////////////

// Groups defined from schema:
// {
//   "type": "array",
//   "items": {
//     "title": "Group",
//     "type": "object",
//     "properties": {
//       "name": {
//         "type": "string"
//       },
//       "self": {
//         "type": "string"
//       }
//     }
//   }
// }
type Groups []*Group
