package jiradata

/////////////////////////////////////////////////////////////////////////
// This Code is Generated by SlipScheme Project:
// https://github.com/coryb/slipscheme
//
// Generated with command:
// slipscheme -dir jiradata -pkg jiradata -overwrite schemas/ListofAttachment.json
/////////////////////////////////////////////////////////////////////////
//                            DO NOT EDIT                              //
/////////////////////////////////////////////////////////////////////////

// Group defined from schema:
// {
//   "title": "Group",
//   "type": "object",
//   "properties": {
//     "name": {
//       "type": "string"
//     },
//     "self": {
//       "type": "string"
//     }
//   }
// }
type Group struct {
	Name string `json:"name,omitempty" yaml:"name,omitempty"`
	Self string `json:"self,omitempty" yaml:"self,omitempty"`
}
