package jiradata

/////////////////////////////////////////////////////////////////////////
// This Code is Generated by SlipScheme Project:
// https://github.com/coryb/slipscheme
//
// Generated with command:
// slipscheme -dir jiradata -pkg jiradata -overwrite schemas/SearchResults.json
/////////////////////////////////////////////////////////////////////////
//                            DO NOT EDIT                              //
/////////////////////////////////////////////////////////////////////////

// Histories defined from schema:
// {
//   "title": "histories",
//   "type": "array",
//   "items": {
//     "title": "Change History",
//     "type": "object",
//     "properties": {
//       "author": {
//         "title": "User",
//         "type": "object",
//         "properties": {
//           "accountId": {
//             "title": "accountId",
//             "type": "string"
//           },
//           "active": {
//             "title": "active",
//             "type": "boolean"
//           },
//           "avatarUrls": {
//             "title": "avatarUrls",
//             "type": "object",
//             "patternProperties": {
//               ".+": {
//                 "type": "string"
//               }
//             }
//           },
//           "displayName": {
//             "title": "displayName",
//             "type": "string"
//           },
//           "emailAddress": {
//             "title": "emailAddress",
//             "type": "string"
//           },
//           "key": {
//             "title": "key",
//             "type": "string"
//           },
//           "name": {
//             "title": "name",
//             "type": "string"
//           },
//           "self": {
//             "title": "self",
//             "type": "string"
//           },
//           "timeZone": {
//             "title": "timeZone",
//             "type": "string"
//           }
//         }
//       },
//       "created": {
//         "title": "created",
//         "type": "string"
//       },
//       "historyMetadata": {
//         "title": "History Metadata",
//         "type": "object",
//         "properties": {
//           "activityDescription": {
//             "title": "activityDescription",
//             "type": "string"
//           },
//           "activityDescriptionKey": {
//             "title": "activityDescriptionKey",
//             "type": "string"
//           },
//           "actor": {
//             "title": "History Metadata Participant",
//             "type": "object",
//             "properties": {
//               "avatarUrl": {
//                 "type": "string"
//               },
//               "displayName": {
//                 "type": "string"
//               },
//               "displayNameKey": {
//                 "type": "string"
//               },
//               "id": {
//                 "type": "string"
//               },
//               "type": {
//                 "type": "string"
//               },
//               "url": {
//                 "type": "string"
//               }
//             }
//           },
//           "cause": {
//             "title": "History Metadata Participant",
//             "type": "object",
//             "properties": {
//               "avatarUrl": {
//                 "type": "string"
//               },
//               "displayName": {
//                 "type": "string"
//               },
//               "displayNameKey": {
//                 "type": "string"
//               },
//               "id": {
//                 "type": "string"
//               },
//               "type": {
//                 "type": "string"
//               },
//               "url": {
//                 "type": "string"
//               }
//             }
//           },
//           "description": {
//             "title": "description",
//             "type": "string"
//           },
//           "descriptionKey": {
//             "title": "descriptionKey",
//             "type": "string"
//           },
//           "emailDescription": {
//             "title": "emailDescription",
//             "type": "string"
//           },
//           "emailDescriptionKey": {
//             "title": "emailDescriptionKey",
//             "type": "string"
//           },
//           "extraData": {
//             "title": "extraData",
//             "type": "object",
//             "patternProperties": {
//               ".+": {
//                 "type": "string"
//               }
//             }
//           },
//           "generator": {
//             "title": "History Metadata Participant",
//             "type": "object",
//             "properties": {
//               "avatarUrl": {
//                 "type": "string"
//               },
//               "displayName": {
//                 "type": "string"
//               },
//               "displayNameKey": {
//                 "type": "string"
//               },
//               "id": {
//                 "type": "string"
//               },
//               "type": {
//                 "type": "string"
//               },
//               "url": {
//                 "type": "string"
//               }
//             }
//           },
//           "type": {
//             "title": "type",
//             "type": "string"
//           }
//         }
//       },
//       "id": {
//         "title": "id",
//         "type": "string"
//       },
//       "items": {
//         "title": "items",
//         "type": "array",
//         "items": {
//           "title": "Change Item",
//           "type": "object",
//           "properties": {
//             "field": {
//               "title": "field",
//               "type": "string"
//             },
//             "fieldId": {
//               "title": "fieldId",
//               "type": "string"
//             },
//             "fieldtype": {
//               "title": "fieldtype",
//               "type": "string"
//             },
//             "from": {
//               "title": "from",
//               "type": "string"
//             },
//             "fromString": {
//               "title": "fromString",
//               "type": "string"
//             },
//             "to": {
//               "title": "to",
//               "type": "string"
//             },
//             "toString": {
//               "title": "toString",
//               "type": "string"
//             }
//           }
//         }
//       }
//     }
//   }
// }
type Histories []*ChangeHistory
