package jiradata

/////////////////////////////////////////////////////////////////////////
// This Code is Generated by SlipScheme Project:
// https://github.com/coryb/slipscheme
//
// Generated with command:
// slipscheme -dir jiradata -pkg jiradata -overwrite schemas/SearchResults.json
/////////////////////////////////////////////////////////////////////////
//                            DO NOT EDIT                              //
/////////////////////////////////////////////////////////////////////////

// HistoryMetadata defined from schema:
// {
//   "title": "History Metadata",
//   "type": "object",
//   "properties": {
//     "activityDescription": {
//       "title": "activityDescription",
//       "type": "string"
//     },
//     "activityDescriptionKey": {
//       "title": "activityDescriptionKey",
//       "type": "string"
//     },
//     "actor": {
//       "title": "History Metadata Participant",
//       "type": "object",
//       "properties": {
//         "avatarUrl": {
//           "type": "string"
//         },
//         "displayName": {
//           "type": "string"
//         },
//         "displayNameKey": {
//           "type": "string"
//         },
//         "id": {
//           "type": "string"
//         },
//         "type": {
//           "type": "string"
//         },
//         "url": {
//           "type": "string"
//         }
//       }
//     },
//     "cause": {
//       "title": "History Metadata Participant",
//       "type": "object",
//       "properties": {
//         "avatarUrl": {
//           "type": "string"
//         },
//         "displayName": {
//           "type": "string"
//         },
//         "displayNameKey": {
//           "type": "string"
//         },
//         "id": {
//           "type": "string"
//         },
//         "type": {
//           "type": "string"
//         },
//         "url": {
//           "type": "string"
//         }
//       }
//     },
//     "description": {
//       "title": "description",
//       "type": "string"
//     },
//     "descriptionKey": {
//       "title": "descriptionKey",
//       "type": "string"
//     },
//     "emailDescription": {
//       "title": "emailDescription",
//       "type": "string"
//     },
//     "emailDescriptionKey": {
//       "title": "emailDescriptionKey",
//       "type": "string"
//     },
//     "extraData": {
//       "title": "extraData",
//       "type": "object",
//       "patternProperties": {
//         ".+": {
//           "type": "string"
//         }
//       }
//     },
//     "generator": {
//       "title": "History Metadata Participant",
//       "type": "object",
//       "properties": {
//         "avatarUrl": {
//           "type": "string"
//         },
//         "displayName": {
//           "type": "string"
//         },
//         "displayNameKey": {
//           "type": "string"
//         },
//         "id": {
//           "type": "string"
//         },
//         "type": {
//           "type": "string"
//         },
//         "url": {
//           "type": "string"
//         }
//       }
//     },
//     "type": {
//       "title": "type",
//       "type": "string"
//     }
//   }
// }
type HistoryMetadata struct {
	ActivityDescription    string                      `json:"activityDescription,omitempty" yaml:"activityDescription,omitempty"`
	ActivityDescriptionKey string                      `json:"activityDescriptionKey,omitempty" yaml:"activityDescriptionKey,omitempty"`
	Actor                  *HistoryMetadataParticipant `json:"actor,omitempty" yaml:"actor,omitempty"`
	Cause                  *HistoryMetadataParticipant `json:"cause,omitempty" yaml:"cause,omitempty"`
	Description            string                      `json:"description,omitempty" yaml:"description,omitempty"`
	DescriptionKey         string                      `json:"descriptionKey,omitempty" yaml:"descriptionKey,omitempty"`
	EmailDescription       string                      `json:"emailDescription,omitempty" yaml:"emailDescription,omitempty"`
	EmailDescriptionKey    string                      `json:"emailDescriptionKey,omitempty" yaml:"emailDescriptionKey,omitempty"`
	ExtraData              map[string]string           `json:"extraData,omitempty" yaml:"extraData,omitempty"`
	Generator              *HistoryMetadataParticipant `json:"generator,omitempty" yaml:"generator,omitempty"`
	Type                   string                      `json:"type,omitempty" yaml:"type,omitempty"`
}
