package jiradata

/////////////////////////////////////////////////////////////////////////
// This Code is Generated by SlipScheme Project:
// https://github.com/coryb/slipscheme
//
// Generated with command:
// slipscheme -dir jiradata -pkg jiradata -overwrite schemas/IssueLinkTypes.json
/////////////////////////////////////////////////////////////////////////
//                            DO NOT EDIT                              //
/////////////////////////////////////////////////////////////////////////

// IssueLinkTypes defined from schema:
// {
//   "title": "issueLinkTypes",
//   "type": "array",
//   "items": {
//     "title": "Issue Link Type",
//     "type": "object",
//     "properties": {
//       "id": {
//         "title": "id",
//         "type": "string"
//       },
//       "inward": {
//         "title": "inward",
//         "type": "string"
//       },
//       "name": {
//         "title": "name",
//         "type": "string"
//       },
//       "outward": {
//         "title": "outward",
//         "type": "string"
//       },
//       "self": {
//         "title": "self",
//         "type": "string"
//       }
//     }
//   }
// }
type IssueLinkTypes []*IssueLinkType
