package jiradata

/////////////////////////////////////////////////////////////////////////
// This Code is Generated by SlipScheme Project:
// https://github.com/coryb/slipscheme
//
// Generated with command:
// slipscheme -dir jiradata -pkg jiradata -overwrite schemas/LinkIssueRequest.json
/////////////////////////////////////////////////////////////////////////
//                            DO NOT EDIT                              //
/////////////////////////////////////////////////////////////////////////

// IssueRef defined from schema:
// {
//   "title": "Issue Ref",
//   "type": "object",
//   "properties": {
//     "fields": {
//       "title": "Fields",
//       "type": "object",
//       "properties": {
//         "issuetype": {
//           "title": "Issue Type",
//           "type": "object",
//           "properties": {
//             "avatarId": {
//               "type": "integer"
//             },
//             "description": {
//               "type": "string"
//             },
//             "iconUrl": {
//               "type": "string"
//             },
//             "id": {
//               "type": "string"
//             },
//             "name": {
//               "type": "string"
//             },
//             "subtask": {
//               "type": "boolean"
//             }
//           }
//         },
//         "priority": {
//           "title": "Priority",
//           "type": "object",
//           "properties": {
//             "description": {
//               "type": "string"
//             },
//             "iconUrl": {
//               "type": "string"
//             },
//             "id": {
//               "type": "string"
//             },
//             "name": {
//               "type": "string"
//             },
//             "statusColor": {
//               "type": "string"
//             }
//           }
//         },
//         "status": {
//           "title": "Status",
//           "type": "object",
//           "properties": {
//             "description": {
//               "type": "string"
//             },
//             "iconUrl": {
//               "type": "string"
//             },
//             "id": {
//               "type": "string"
//             },
//             "name": {
//               "type": "string"
//             },
//             "statusCategory": {
//               "title": "Status Category",
//               "type": "object",
//               "properties": {
//                 "colorName": {
//                   "type": "string"
//                 },
//                 "id": {
//                   "type": "integer"
//                 },
//                 "key": {
//                   "type": "string"
//                 },
//                 "name": {
//                   "type": "string"
//                 }
//               }
//             },
//             "statusColor": {
//               "type": "string"
//             }
//           }
//         },
//         "summary": {
//           "type": "string"
//         }
//       }
//     },
//     "id": {
//       "type": "string"
//     },
//     "key": {
//       "type": "string"
//     }
//   }
// }
type IssueRef struct {
	Fields *Fields `json:"fields,omitempty" yaml:"fields,omitempty"`
	ID     string  `json:"id,omitempty" yaml:"id,omitempty"`
	Key    string  `json:"key,omitempty" yaml:"key,omitempty"`
}
