package jiradata

/////////////////////////////////////////////////////////////////////////
// This Code is Generated by SlipScheme Project:
// https://github.com/coryb/slipscheme
//
// Generated with command:
// slipscheme -dir jiradata -pkg jiradata -overwrite schemas/LinkIssueRequest.json
/////////////////////////////////////////////////////////////////////////
//                            DO NOT EDIT                              //
/////////////////////////////////////////////////////////////////////////

// IssueLinkType defined from schema:
// {
//   "title": "Issue Link Type",
//   "type": "object",
//   "properties": {
//     "id": {
//       "title": "id",
//       "type": "string"
//     },
//     "inward": {
//       "title": "inward",
//       "type": "string"
//     },
//     "name": {
//       "title": "name",
//       "type": "string"
//     },
//     "outward": {
//       "title": "outward",
//       "type": "string"
//     }
//   }
// }
type IssueLinkType struct {
	ID      string `json:"id,omitempty" yaml:"id,omitempty"`
	Inward  string `json:"inward,omitempty" yaml:"inward,omitempty"`
	Name    string `json:"name,omitempty" yaml:"name,omitempty"`
	Outward string `json:"outward,omitempty" yaml:"outward,omitempty"`
}
