package jiradata

/////////////////////////////////////////////////////////////////////////
// This Code is Generated by SlipScheme Project:
// https://github.com/coryb/slipscheme
//
// Generated with command:
// slipscheme -dir jiradata -pkg jiradata -overwrite schemas/Project.json
/////////////////////////////////////////////////////////////////////////
//                            DO NOT EDIT                              //
/////////////////////////////////////////////////////////////////////////

// IssueType defined from schema:
// {
//   "title": "Issue Type",
//   "type": "object",
//   "properties": {
//     "avatarId": {
//       "title": "avatarId",
//       "type": "integer"
//     },
//     "description": {
//       "title": "description",
//       "type": "string"
//     },
//     "iconUrl": {
//       "title": "iconUrl",
//       "type": "string"
//     },
//     "id": {
//       "title": "id",
//       "type": "string"
//     },
//     "name": {
//       "title": "name",
//       "type": "string"
//     },
//     "self": {
//       "title": "self",
//       "type": "string"
//     },
//     "subtask": {
//       "title": "subtask",
//       "type": "boolean"
//     }
//   }
// }
type IssueType struct {
	AvatarID    int          `json:"avatarId,omitempty" yaml:"avatarId,omitempty"`
	Description string       `json:"description,omitempty" yaml:"description,omitempty"`
	Fields      FieldMetaMap `json:"fields,omitempty" yaml:"fields,omitempty"`
	IconURL     string       `json:"iconUrl,omitempty" yaml:"iconUrl,omitempty"`
	ID          string       `json:"id,omitempty" yaml:"id,omitempty"`
	Name        string       `json:"name,omitempty" yaml:"name,omitempty"`
	Self        string       `json:"self,omitempty" yaml:"self,omitempty"`
	Subtask     bool         `json:"subtask,omitempty" yaml:"subtask,omitempty"`
}
