package jiradata

/////////////////////////////////////////////////////////////////////////
// This Code is Generated by SlipScheme Project:
// https://github.com/coryb/slipscheme
//
// Generated with command:
// slipscheme -dir jiradata -pkg jiradata -overwrite schemas/IssueUpdate.json
/////////////////////////////////////////////////////////////////////////
//                            DO NOT EDIT                              //
/////////////////////////////////////////////////////////////////////////

// IssueUpdate defined from schema:
// {
//   "title": "Issue Update",
//   "id": "https://docs.atlassian.com/jira/REST/schema/issue-update#",
//   "type": "object",
//   "definitions": {
//     "history-metadata-participant": {
//       "title": "History Metadata Participant",
//       "type": "object",
//       "properties": {
//         "avatarUrl": {
//           "type": "string"
//         },
//         "displayName": {
//           "type": "string"
//         },
//         "displayNameKey": {
//           "type": "string"
//         },
//         "id": {
//           "type": "string"
//         },
//         "type": {
//           "type": "string"
//         },
//         "url": {
//           "type": "string"
//         }
//       }
//     }
//   },
//   "properties": {
//     "fields": {
//       "title": "fields",
//       "type": "object",
//       "patternProperties": {
//         ".+": {}
//       }
//     },
//     "historyMetadata": {
//       "title": "History Metadata",
//       "type": "object",
//       "properties": {
//         "activityDescription": {
//           "title": "activityDescription",
//           "type": "string"
//         },
//         "activityDescriptionKey": {
//           "title": "activityDescriptionKey",
//           "type": "string"
//         },
//         "actor": {
//           "title": "History Metadata Participant",
//           "type": "object",
//           "properties": {
//             "avatarUrl": {
//               "type": "string"
//             },
//             "displayName": {
//               "type": "string"
//             },
//             "displayNameKey": {
//               "type": "string"
//             },
//             "id": {
//               "type": "string"
//             },
//             "type": {
//               "type": "string"
//             },
//             "url": {
//               "type": "string"
//             }
//           }
//         },
//         "cause": {
//           "title": "History Metadata Participant",
//           "type": "object",
//           "properties": {
//             "avatarUrl": {
//               "type": "string"
//             },
//             "displayName": {
//               "type": "string"
//             },
//             "displayNameKey": {
//               "type": "string"
//             },
//             "id": {
//               "type": "string"
//             },
//             "type": {
//               "type": "string"
//             },
//             "url": {
//               "type": "string"
//             }
//           }
//         },
//         "description": {
//           "title": "description",
//           "type": "string"
//         },
//         "descriptionKey": {
//           "title": "descriptionKey",
//           "type": "string"
//         },
//         "emailDescription": {
//           "title": "emailDescription",
//           "type": "string"
//         },
//         "emailDescriptionKey": {
//           "title": "emailDescriptionKey",
//           "type": "string"
//         },
//         "extraData": {
//           "title": "extraData",
//           "type": "object",
//           "patternProperties": {
//             ".+": {
//               "type": "string"
//             }
//           }
//         },
//         "generator": {
//           "title": "History Metadata Participant",
//           "type": "object",
//           "properties": {
//             "avatarUrl": {
//               "type": "string"
//             },
//             "displayName": {
//               "type": "string"
//             },
//             "displayNameKey": {
//               "type": "string"
//             },
//             "id": {
//               "type": "string"
//             },
//             "type": {
//               "type": "string"
//             },
//             "url": {
//               "type": "string"
//             }
//           }
//         },
//         "type": {
//           "title": "type",
//           "type": "string"
//         }
//       }
//     },
//     "properties": {
//       "title": "properties",
//       "type": "array",
//       "items": {
//         "title": "Entity Property",
//         "type": "object",
//         "properties": {
//           "key": {
//             "title": "key",
//             "type": "string"
//           },
//           "value": {
//             "title": "value"
//           }
//         }
//       }
//     },
//     "transition": {
//       "title": "Transition",
//       "type": "object",
//       "properties": {
//         "fields": {
//           "title": "fields",
//           "type": "object",
//           "patternProperties": {
//             ".+": {
//               "title": "Field Meta",
//               "type": "object",
//               "properties": {
//                 "allowedValues": {
//                   "title": "allowedValues",
//                   "type": "array",
//                   "items": {}
//                 },
//                 "autoCompleteUrl": {
//                   "title": "autoCompleteUrl",
//                   "type": "string"
//                 },
//                 "defaultValue": {
//                   "title": "defaultValue"
//                 },
//                 "hasDefaultValue": {
//                   "title": "hasDefaultValue",
//                   "type": "boolean"
//                 },
//                 "key": {
//                   "title": "key",
//                   "type": "string"
//                 },
//                 "name": {
//                   "title": "name",
//                   "type": "string"
//                 },
//                 "operations": {
//                   "title": "operations",
//                   "type": "array",
//                   "items": {
//                     "type": "string"
//                   }
//                 },
//                 "required": {
//                   "title": "required",
//                   "type": "boolean"
//                 },
//                 "schema": {
//                   "title": "Json Type",
//                   "type": "object",
//                   "properties": {
//                     "custom": {
//                       "title": "custom",
//                       "type": "string"
//                     },
//                     "customId": {
//                       "title": "customId",
//                       "type": "integer"
//                     },
//                     "items": {
//                       "title": "items",
//                       "type": "string"
//                     },
//                     "system": {
//                       "title": "system",
//                       "type": "string"
//                     },
//                     "type": {
//                       "title": "type",
//                       "type": "string"
//                     }
//                   }
//                 }
//               }
//             }
//           }
//         },
//         "hasScreen": {
//           "title": "hasScreen",
//           "type": "boolean"
//         },
//         "id": {
//           "title": "id",
//           "type": "string"
//         },
//         "name": {
//           "title": "name",
//           "type": "string"
//         },
//         "to": {
//           "title": "Status",
//           "type": "object",
//           "properties": {
//             "description": {
//               "title": "description",
//               "type": "string"
//             },
//             "iconUrl": {
//               "title": "iconUrl",
//               "type": "string"
//             },
//             "id": {
//               "title": "id",
//               "type": "string"
//             },
//             "name": {
//               "title": "name",
//               "type": "string"
//             },
//             "statusCategory": {
//               "title": "Status Category",
//               "type": "object",
//               "properties": {
//                 "colorName": {
//                   "title": "colorName",
//                   "type": "string"
//                 },
//                 "id": {
//                   "title": "id",
//                   "type": "integer"
//                 },
//                 "key": {
//                   "title": "key",
//                   "type": "string"
//                 },
//                 "name": {
//                   "title": "name",
//                   "type": "string"
//                 }
//               }
//             },
//             "statusColor": {
//               "title": "statusColor",
//               "type": "string"
//             }
//           }
//         }
//       }
//     },
//     "update": {
//       "title": "update",
//       "type": "object",
//       "patternProperties": {
//         ".+": {
//           "type": "array",
//           "items": {
//             "title": "Field Operation",
//             "type": "object"
//           }
//         }
//       }
//     }
//   }
// }
type IssueUpdate struct {
	Fields          map[string]interface{} `json:"fields,omitempty" yaml:"fields,omitempty"`
	HistoryMetadata *HistoryMetadata       `json:"historyMetadata,omitempty" yaml:"historyMetadata,omitempty"`
	Properties      Properties             `json:"properties,omitempty" yaml:"properties,omitempty"`
	Transition      *Transition            `json:"transition,omitempty" yaml:"transition,omitempty"`
	Update          FieldOperationsMap     `json:"update,omitempty" yaml:"update,omitempty"`
}
