package jiradata

/////////////////////////////////////////////////////////////////////////
// This Code is Generated by SlipScheme Project:
// https://github.com/coryb/slipscheme
//
// Generated with command:
// slipscheme -dir jiradata -pkg jiradata -overwrite schemas/IssueCreateResponse.json
/////////////////////////////////////////////////////////////////////////
//                            DO NOT EDIT                              //
/////////////////////////////////////////////////////////////////////////

// IssueCreateResponse defined from schema:
// {
//   "title": "Issue Create Response",
//   "id": "https://docs.atlassian.com/jira/REST/schema/issue-create-response#",
//   "type": "object",
//   "properties": {
//     "id": {
//       "title": "id",
//       "type": "string"
//     },
//     "key": {
//       "title": "key",
//       "type": "string"
//     },
//     "self": {
//       "title": "self",
//       "type": "string"
//     }
//   }
// }
type IssueCreateResponse struct {
	ID   string `json:"id,omitempty" yaml:"id,omitempty"`
	Key  string `json:"key,omitempty" yaml:"key,omitempty"`
	Self string `json:"self,omitempty" yaml:"self,omitempty"`
}
