package jiradata

/////////////////////////////////////////////////////////////////////////
// This Code is Generated by SlipScheme Project:
// https://github.com/coryb/slipscheme
//
// Generated with command:
// slipscheme -dir jiradata -pkg jiradata -overwrite schemas/SearchResults.json
/////////////////////////////////////////////////////////////////////////
//                            DO NOT EDIT                              //
/////////////////////////////////////////////////////////////////////////

// JSONTypeMap defined from schema:
// {
//   "title": "schema",
//   "type": "object",
//   "patternProperties": {
//     ".+": {
//       "title": "Json Type",
//       "type": "object",
//       "properties": {
//         "custom": {
//           "type": "string"
//         },
//         "customId": {
//           "type": "integer"
//         },
//         "items": {
//           "type": "string"
//         },
//         "system": {
//           "type": "string"
//         },
//         "type": {
//           "type": "string"
//         }
//       }
//     }
//   }
// }
type JSONTypeMap map[string]*JSONType
