package jiradata

/////////////////////////////////////////////////////////////////////////
// This Code is Generated by SlipScheme Project:
// https://github.com/coryb/slipscheme
//
// Generated with command:
// slipscheme -dir jiradata -pkg jiradata -overwrite schemas/TransitionsMeta.json
/////////////////////////////////////////////////////////////////////////
//                            DO NOT EDIT                              //
/////////////////////////////////////////////////////////////////////////

// JSONType defined from schema:
// {
//   "title": "Json Type",
//   "type": "object",
//   "properties": {
//     "custom": {
//       "title": "custom",
//       "type": "string"
//     },
//     "customId": {
//       "title": "customId",
//       "type": "integer"
//     },
//     "items": {
//       "title": "items",
//       "type": "string"
//     },
//     "system": {
//       "title": "system",
//       "type": "string"
//     },
//     "type": {
//       "title": "type",
//       "type": "string"
//     }
//   }
// }
type JSONType struct {
	Custom   string `json:"custom,omitempty" yaml:"custom,omitempty"`
	CustomID int    `json:"customId,omitempty" yaml:"customId,omitempty"`
	Items    string `json:"items,omitempty" yaml:"items,omitempty"`
	System   string `json:"system,omitempty" yaml:"system,omitempty"`
	Type     string `json:"type,omitempty" yaml:"type,omitempty"`
}
