package jiradata

/////////////////////////////////////////////////////////////////////////
// This Code is Generated by SlipScheme Project:
// https://github.com/coryb/slipscheme
//
// Generated with command:
// slipscheme -dir jiradata -pkg jiradata -overwrite schemas/ListofAttachment.json
/////////////////////////////////////////////////////////////////////////
//                            DO NOT EDIT                              //
/////////////////////////////////////////////////////////////////////////

// ListOfAttachment defined from schema:
// {
//   "title": "List of Attachment",
//   "id": "https://docs.atlassian.com/jira/REST/schema/list-of-attachment#",
//   "type": "array",
//   "definitions": {
//     "simple-list-wrapper": {
//       "title": "Simple List Wrapper",
//       "type": "object",
//       "properties": {
//         "items": {
//           "type": "array",
//           "items": {
//             "title": "Group",
//             "type": "object",
//             "properties": {
//               "name": {
//                 "type": "string"
//               },
//               "self": {
//                 "type": "string"
//               }
//             }
//           }
//         },
//         "max-results": {
//           "type": "integer"
//         },
//         "size": {
//           "type": "integer"
//         }
//       }
//     }
//   },
//   "items": {
//     "title": "Attachment",
//     "type": "object",
//     "properties": {
//       "author": {
//         "title": "User",
//         "type": "object",
//         "properties": {
//           "accountId": {
//             "title": "accountId",
//             "type": "string"
//           },
//           "active": {
//             "title": "active",
//             "type": "boolean"
//           },
//           "applicationRoles": {
//             "title": "Simple List Wrapper",
//             "type": "object",
//             "properties": {
//               "items": {
//                 "type": "array",
//                 "items": {
//                   "title": "Group",
//                   "type": "object",
//                   "properties": {
//                     "name": {
//                       "type": "string"
//                     },
//                     "self": {
//                       "type": "string"
//                     }
//                   }
//                 }
//               },
//               "max-results": {
//                 "type": "integer"
//               },
//               "size": {
//                 "type": "integer"
//               }
//             }
//           },
//           "avatarUrls": {
//             "title": "avatarUrls",
//             "type": "object",
//             "patternProperties": {
//               ".+": {
//                 "type": "string"
//               }
//             }
//           },
//           "displayName": {
//             "title": "displayName",
//             "type": "string"
//           },
//           "emailAddress": {
//             "title": "emailAddress",
//             "type": "string"
//           },
//           "expand": {
//             "title": "expand",
//             "type": "string"
//           },
//           "groups": {
//             "title": "Simple List Wrapper",
//             "type": "object",
//             "properties": {
//               "items": {
//                 "type": "array",
//                 "items": {
//                   "title": "Group",
//                   "type": "object",
//                   "properties": {
//                     "name": {
//                       "type": "string"
//                     },
//                     "self": {
//                       "type": "string"
//                     }
//                   }
//                 }
//               },
//               "max-results": {
//                 "type": "integer"
//               },
//               "size": {
//                 "type": "integer"
//               }
//             }
//           },
//           "key": {
//             "title": "key",
//             "type": "string"
//           },
//           "locale": {
//             "title": "locale",
//             "type": "string"
//           },
//           "name": {
//             "title": "name",
//             "type": "string"
//           },
//           "self": {
//             "title": "self",
//             "type": "string"
//           },
//           "timeZone": {
//             "title": "timeZone",
//             "type": "string"
//           }
//         }
//       },
//       "content": {
//         "title": "content",
//         "type": "string"
//       },
//       "created": {
//         "title": "created",
//         "type": "string"
//       },
//       "filename": {
//         "title": "filename",
//         "type": "string"
//       },
//       "id": {
//         "title": "id",
//         "type": "integer"
//       },
//       "mimeType": {
//         "title": "mimeType",
//         "type": "string"
//       },
//       "properties": {
//         "title": "properties",
//         "type": "object",
//         "patternProperties": {
//           ".+": {}
//         }
//       },
//       "self": {
//         "title": "self",
//         "type": "string"
//       },
//       "size": {
//         "title": "size",
//         "type": "integer"
//       },
//       "thumbnail": {
//         "title": "thumbnail",
//         "type": "string"
//       }
//     }
//   }
// }
type ListOfAttachment []*Attachment
