package jiradata

/////////////////////////////////////////////////////////////////////////
// This Code is Generated by SlipScheme Project:
// https://github.com/coryb/slipscheme
//
// Generated with command:
// slipscheme -dir jiradata -pkg jiradata -overwrite schemas/SearchResults.json
/////////////////////////////////////////////////////////////////////////
//                            DO NOT EDIT                              //
/////////////////////////////////////////////////////////////////////////

// Opsbar defined from schema:
// {
//   "title": "Opsbar",
//   "type": "object",
//   "properties": {
//     "linkGroups": {
//       "title": "linkGroups",
//       "type": "array",
//       "items": {
//         "title": "Link Group",
//         "type": "object",
//         "properties": {
//           "groups": {
//             "type": "array",
//             "items": {
//               "$ref": "#/definitions/link-group"
//             }
//           },
//           "header": {
//             "$ref": "#/definitions/simple-link"
//           },
//           "id": {
//             "type": "string"
//           },
//           "links": {
//             "type": "array",
//             "items": {
//               "$ref": "#/definitions/simple-link"
//             }
//           },
//           "styleClass": {
//             "type": "string"
//           },
//           "weight": {
//             "type": "integer"
//           }
//         }
//       }
//     }
//   }
// }
type Opsbar struct {
	LinkGroups LinkGroups `json:"linkGroups,omitempty" yaml:"linkGroups,omitempty"`
}
