package jiradata

/////////////////////////////////////////////////////////////////////////
// This Code is Generated by SlipScheme Project:
// https://github.com/coryb/slipscheme
//
// Generated with command:
// slipscheme -dir jiradata schema/IssueTypes.json
/////////////////////////////////////////////////////////////////////////
//                            DO NOT EDIT                              //
/////////////////////////////////////////////////////////////////////////

// PageOfCreateMetaIssueType defined from schema:
//
//	{
//	  "title": "Page of Create Meta Issue Type",
//	  "id": "https://docs.atlassian.com/jira/REST/schema/page-of-create-meta-issue-type#",
//	  "type": "object",
//	  "properties": {
//	    "last": {
//	      "title": "last",
//	      "type": "boolean"
//	    },
//	    "size": {
//	      "title": "size",
//	      "type": "integer"
//	    },
//	    "start": {
//	      "title": "start",
//	      "type": "integer"
//	    },
//	    "total": {
//	      "title": "total",
//	      "type": "integer"
//	    },
//	    "values": {
//	      "title": "values",
//	      "type": "array",
//	      "items": {
//	        "title": "Create Meta Issue Type",
//	        "type": "object",
//	        "properties": {
//	          "avatarId": {
//	            "title": "avatarId",
//	            "type": "integer"
//	          },
//	          "description": {
//	            "title": "description",
//	            "type": "string"
//	          },
//	          "expand": {
//	            "title": "expand",
//	            "type": "string"
//	          },
//	          "fields": {
//	            "title": "fields",
//	            "type": "object",
//	            "patternProperties": {
//	              ".+": {
//	                "title": "Field Meta",
//	                "type": "object",
//	                "properties": {
//	                  "allowedValues": {
//	                    "title": "allowedValues",
//	                    "type": "array",
//	                    "items": {}
//	                  },
//	                  "autoCompleteUrl": {
//	                    "title": "autoCompleteUrl",
//	                    "type": "string"
//	                  },
//	                  "defaultValue": {
//	                    "title": "defaultValue"
//	                  },
//	                  "fieldId": {
//	                    "title": "fieldId",
//	                    "type": "string"
//	                  },
//	                  "hasDefaultValue": {
//	                    "title": "hasDefaultValue",
//	                    "type": "boolean"
//	                  },
//	                  "name": {
//	                    "title": "name",
//	                    "type": "string"
//	                  },
//	                  "operations": {
//	                    "title": "operations",
//	                    "type": "array",
//	                    "items": {
//	                      "type": "string"
//	                    }
//	                  },
//	                  "required": {
//	                    "title": "required",
//	                    "type": "boolean"
//	                  },
//	                  "schema": {
//	                    "title": "Json Type",
//	                    "type": "object",
//	                    "properties": {
//	                      "custom": {
//	                        "title": "custom",
//	                        "type": "string"
//	                      },
//	                      "customId": {
//	                        "title": "customId",
//	                        "type": "integer"
//	                      },
//	                      "items": {
//	                        "title": "items",
//	                        "type": "string"
//	                      },
//	                      "system": {
//	                        "title": "system",
//	                        "type": "string"
//	                      },
//	                      "type": {
//	                        "title": "type",
//	                        "type": "string"
//	                      }
//	                    }
//	                  }
//	                }
//	              }
//	            }
//	          },
//	          "iconUrl": {
//	            "title": "iconUrl",
//	            "type": "string"
//	          },
//	          "id": {
//	            "title": "id",
//	            "type": "string"
//	          },
//	          "name": {
//	            "title": "name",
//	            "type": "string"
//	          },
//	          "self": {
//	            "title": "self",
//	            "type": "string"
//	          },
//	          "subtask": {
//	            "title": "subtask",
//	            "type": "boolean"
//	          }
//	        }
//	      }
//	    }
//	  }
//	}
type PageOfCreateMetaIssueType struct {
	Last   bool   `json:"last,omitempty" yaml:"last,omitempty"`
	Size   int    `json:"size,omitempty" yaml:"size,omitempty"`
	Start  int    `json:"start,omitempty" yaml:"start,omitempty"`
	Total  int    `json:"total,omitempty" yaml:"total,omitempty"`
	Values Values `json:"values,omitempty" yaml:"values,omitempty"`
}
