package jiradata

/////////////////////////////////////////////////////////////////////////
// This Code is Generated by SlipScheme Project:
// https://github.com/coryb/slipscheme
//
// Generated with command:
// slipscheme -dir jiradata -pkg jiradata -overwrite schemas/PageofVersion.json
/////////////////////////////////////////////////////////////////////////
//                            DO NOT EDIT                              //
/////////////////////////////////////////////////////////////////////////

// PageOfVersion defined from schema:
// {
//   "title": "Page of Version",
//   "id": "https://docs.atlassian.com/jira/REST/schema/page-of-version#",
//   "type": "object",
//   "properties": {
//     "isLast": {
//       "title": "isLast",
//       "type": "boolean"
//     },
//     "maxResults": {
//       "title": "maxResults",
//       "type": "integer"
//     },
//     "nextPage": {
//       "title": "nextPage",
//       "type": "string"
//     },
//     "self": {
//       "title": "self",
//       "type": "string"
//     },
//     "startAt": {
//       "title": "startAt",
//       "type": "integer"
//     },
//     "total": {
//       "title": "total",
//       "type": "integer"
//     },
//     "values": {
//       "title": "values",
//       "type": "array",
//       "items": {
//         "title": "Version",
//         "type": "object",
//         "properties": {
//           "archived": {
//             "title": "archived",
//             "type": "boolean"
//           },
//           "description": {
//             "title": "description",
//             "type": "string"
//           },
//           "expand": {
//             "title": "expand",
//             "type": "string"
//           },
//           "id": {
//             "title": "id",
//             "type": "string"
//           },
//           "moveUnfixedIssuesTo": {
//             "title": "moveUnfixedIssuesTo",
//             "type": "string"
//           },
//           "name": {
//             "title": "name",
//             "type": "string"
//           },
//           "operations": {
//             "title": "operations",
//             "type": "array",
//             "items": {
//               "title": "Simple Link",
//               "type": "object",
//               "properties": {
//                 "href": {
//                   "title": "href",
//                   "type": "string"
//                 },
//                 "iconClass": {
//                   "title": "iconClass",
//                   "type": "string"
//                 },
//                 "id": {
//                   "title": "id",
//                   "type": "string"
//                 },
//                 "label": {
//                   "title": "label",
//                   "type": "string"
//                 },
//                 "styleClass": {
//                   "title": "styleClass",
//                   "type": "string"
//                 },
//                 "title": {
//                   "title": "title",
//                   "type": "string"
//                 },
//                 "weight": {
//                   "title": "weight",
//                   "type": "integer"
//                 }
//               }
//             }
//           },
//           "overdue": {
//             "title": "overdue",
//             "type": "boolean"
//           },
//           "project": {
//             "title": "project",
//             "type": "string"
//           },
//           "projectId": {
//             "title": "projectId",
//             "type": "integer"
//           },
//           "released": {
//             "title": "released",
//             "type": "boolean"
//           },
//           "remotelinks": {
//             "title": "remotelinks",
//             "type": "array",
//             "items": {
//               "title": "Remote Entity Link",
//               "type": "object",
//               "properties": {
//                 "link": {
//                   "title": "link"
//                 },
//                 "name": {
//                   "title": "name",
//                   "type": "string"
//                 },
//                 "self": {
//                   "title": "self",
//                   "type": "string"
//                 }
//               }
//             }
//           },
//           "self": {
//             "title": "self",
//             "type": "string"
//           },
//           "userReleaseDate": {
//             "title": "userReleaseDate",
//             "type": "string"
//           },
//           "userStartDate": {
//             "title": "userStartDate",
//             "type": "string"
//           }
//         }
//       }
//     }
//   }
// }
type PageOfVersion struct {
	IsLast     bool   `json:"isLast,omitempty" yaml:"isLast,omitempty"`
	MaxResults int    `json:"maxResults,omitempty" yaml:"maxResults,omitempty"`
	NextPage   string `json:"nextPage,omitempty" yaml:"nextPage,omitempty"`
	Self       string `json:"self,omitempty" yaml:"self,omitempty"`
	StartAt    int    `json:"startAt,omitempty" yaml:"startAt,omitempty"`
	Total      int    `json:"total,omitempty" yaml:"total,omitempty"`
	Values     Values `json:"values,omitempty" yaml:"values,omitempty"`
}
