package jiradata

/////////////////////////////////////////////////////////////////////////
// This Code is Generated by SlipScheme Project:
// https://github.com/coryb/slipscheme
//
// Generated with command:
// slipscheme -dir jiradata -pkg jiradata -overwrite schemas/LinkIssueRequest.json
/////////////////////////////////////////////////////////////////////////
//                            DO NOT EDIT                              //
/////////////////////////////////////////////////////////////////////////

// Priority defined from schema:
// {
//   "title": "Priority",
//   "type": "object",
//   "properties": {
//     "description": {
//       "type": "string"
//     },
//     "iconUrl": {
//       "type": "string"
//     },
//     "id": {
//       "type": "string"
//     },
//     "name": {
//       "type": "string"
//     },
//     "statusColor": {
//       "type": "string"
//     }
//   }
// }
type Priority struct {
	Description string `json:"description,omitempty" yaml:"description,omitempty"`
	IconURL     string `json:"iconUrl,omitempty" yaml:"iconUrl,omitempty"`
	ID          string `json:"id,omitempty" yaml:"id,omitempty"`
	Name        string `json:"name,omitempty" yaml:"name,omitempty"`
	StatusColor string `json:"statusColor,omitempty" yaml:"statusColor,omitempty"`
}
