package jiradata

/////////////////////////////////////////////////////////////////////////
// This Code is Generated by SlipScheme Project:
// https://github.com/coryb/slipscheme
//
// Generated with command:
// slipscheme -dir jiradata -pkg jiradata -overwrite schemas/Project.json
/////////////////////////////////////////////////////////////////////////
//                            DO NOT EDIT                              //
/////////////////////////////////////////////////////////////////////////

// Project defined from schema:
// {
//   "title": "Project",
//   "id": "https://docs.atlassian.com/jira/REST/schema/project#",
//   "type": "object",
//   "definitions": {
//     "simple-list-wrapper": {
//       "title": "Simple List Wrapper",
//       "type": "object",
//       "properties": {
//         "items": {
//           "type": "array",
//           "items": {
//             "title": "Group",
//             "type": "object",
//             "properties": {
//               "name": {
//                 "type": "string"
//               },
//               "self": {
//                 "type": "string"
//               }
//             }
//           }
//         },
//         "max-results": {
//           "type": "integer"
//         },
//         "size": {
//           "type": "integer"
//         }
//       }
//     },
//     "user": {
//       "title": "User",
//       "type": "object",
//       "properties": {
//         "accountId": {
//           "type": "string"
//         },
//         "active": {
//           "type": "boolean"
//         },
//         "applicationRoles": {
//           "$ref": "#/definitions/simple-list-wrapper"
//         },
//         "avatarUrls": {
//           "type": "object",
//           "patternProperties": {
//             ".+": {
//               "type": "string"
//             }
//           }
//         },
//         "displayName": {
//           "type": "string"
//         },
//         "emailAddress": {
//           "type": "string"
//         },
//         "expand": {
//           "type": "string"
//         },
//         "groups": {
//           "$ref": "#/definitions/simple-list-wrapper"
//         },
//         "key": {
//           "type": "string"
//         },
//         "locale": {
//           "type": "string"
//         },
//         "name": {
//           "type": "string"
//         },
//         "self": {
//           "type": "string"
//         },
//         "timeZone": {
//           "type": "string"
//         }
//       }
//     }
//   },
//   "properties": {
//     "assigneeType": {
//       "title": "assigneeType",
//       "type": "string"
//     },
//     "avatarUrls": {
//       "title": "avatarUrls",
//       "type": "object",
//       "patternProperties": {
//         ".+": {
//           "type": "string"
//         }
//       }
//     },
//     "components": {
//       "title": "components",
//       "type": "array",
//       "items": {
//         "title": "Component",
//         "type": "object",
//         "properties": {
//           "assignee": {
//             "title": "User",
//             "type": "object",
//             "properties": {
//               "accountId": {
//                 "type": "string"
//               },
//               "active": {
//                 "type": "boolean"
//               },
//               "applicationRoles": {
//                 "$ref": "#/definitions/simple-list-wrapper"
//               },
//               "avatarUrls": {
//                 "type": "object",
//                 "patternProperties": {
//                   ".+": {
//                     "type": "string"
//                   }
//                 }
//               },
//               "displayName": {
//                 "type": "string"
//               },
//               "emailAddress": {
//                 "type": "string"
//               },
//               "expand": {
//                 "type": "string"
//               },
//               "groups": {
//                 "$ref": "#/definitions/simple-list-wrapper"
//               },
//               "key": {
//                 "type": "string"
//               },
//               "locale": {
//                 "type": "string"
//               },
//               "name": {
//                 "type": "string"
//               },
//               "self": {
//                 "type": "string"
//               },
//               "timeZone": {
//                 "type": "string"
//               }
//             }
//           },
//           "assigneeType": {
//             "title": "assigneeType",
//             "type": "string"
//           },
//           "description": {
//             "title": "description",
//             "type": "string"
//           },
//           "id": {
//             "title": "id",
//             "type": "string"
//           },
//           "isAssigneeTypeValid": {
//             "title": "isAssigneeTypeValid",
//             "type": "boolean"
//           },
//           "lead": {
//             "title": "User",
//             "type": "object",
//             "properties": {
//               "accountId": {
//                 "type": "string"
//               },
//               "active": {
//                 "type": "boolean"
//               },
//               "applicationRoles": {
//                 "$ref": "#/definitions/simple-list-wrapper"
//               },
//               "avatarUrls": {
//                 "type": "object",
//                 "patternProperties": {
//                   ".+": {
//                     "type": "string"
//                   }
//                 }
//               },
//               "displayName": {
//                 "type": "string"
//               },
//               "emailAddress": {
//                 "type": "string"
//               },
//               "expand": {
//                 "type": "string"
//               },
//               "groups": {
//                 "$ref": "#/definitions/simple-list-wrapper"
//               },
//               "key": {
//                 "type": "string"
//               },
//               "locale": {
//                 "type": "string"
//               },
//               "name": {
//                 "type": "string"
//               },
//               "self": {
//                 "type": "string"
//               },
//               "timeZone": {
//                 "type": "string"
//               }
//             }
//           },
//           "leadUserName": {
//             "title": "leadUserName",
//             "type": "string"
//           },
//           "name": {
//             "title": "name",
//             "type": "string"
//           },
//           "project": {
//             "title": "project",
//             "type": "string"
//           },
//           "projectId": {
//             "title": "projectId",
//             "type": "integer"
//           },
//           "realAssignee": {
//             "title": "User",
//             "type": "object",
//             "properties": {
//               "accountId": {
//                 "type": "string"
//               },
//               "active": {
//                 "type": "boolean"
//               },
//               "applicationRoles": {
//                 "$ref": "#/definitions/simple-list-wrapper"
//               },
//               "avatarUrls": {
//                 "type": "object",
//                 "patternProperties": {
//                   ".+": {
//                     "type": "string"
//                   }
//                 }
//               },
//               "displayName": {
//                 "type": "string"
//               },
//               "emailAddress": {
//                 "type": "string"
//               },
//               "expand": {
//                 "type": "string"
//               },
//               "groups": {
//                 "$ref": "#/definitions/simple-list-wrapper"
//               },
//               "key": {
//                 "type": "string"
//               },
//               "locale": {
//                 "type": "string"
//               },
//               "name": {
//                 "type": "string"
//               },
//               "self": {
//                 "type": "string"
//               },
//               "timeZone": {
//                 "type": "string"
//               }
//             }
//           },
//           "realAssigneeType": {
//             "title": "realAssigneeType",
//             "type": "string"
//           },
//           "self": {
//             "title": "self",
//             "type": "string"
//           }
//         }
//       }
//     },
//     "description": {
//       "title": "description",
//       "type": "string"
//     },
//     "email": {
//       "title": "email",
//       "type": "string"
//     },
//     "expand": {
//       "title": "expand",
//       "type": "string"
//     },
//     "id": {
//       "title": "id",
//       "type": "string"
//     },
//     "issueTypes": {
//       "title": "issueTypes",
//       "type": "array",
//       "items": {
//         "title": "Issue Type",
//         "type": "object",
//         "properties": {
//           "avatarId": {
//             "title": "avatarId",
//             "type": "integer"
//           },
//           "description": {
//             "title": "description",
//             "type": "string"
//           },
//           "iconUrl": {
//             "title": "iconUrl",
//             "type": "string"
//           },
//           "id": {
//             "title": "id",
//             "type": "string"
//           },
//           "name": {
//             "title": "name",
//             "type": "string"
//           },
//           "self": {
//             "title": "self",
//             "type": "string"
//           },
//           "subtask": {
//             "title": "subtask",
//             "type": "boolean"
//           }
//         }
//       }
//     },
//     "key": {
//       "title": "key",
//       "type": "string"
//     },
//     "lead": {
//       "title": "User",
//       "type": "object",
//       "properties": {
//         "accountId": {
//           "type": "string"
//         },
//         "active": {
//           "type": "boolean"
//         },
//         "applicationRoles": {
//           "$ref": "#/definitions/simple-list-wrapper"
//         },
//         "avatarUrls": {
//           "type": "object",
//           "patternProperties": {
//             ".+": {
//               "type": "string"
//             }
//           }
//         },
//         "displayName": {
//           "type": "string"
//         },
//         "emailAddress": {
//           "type": "string"
//         },
//         "expand": {
//           "type": "string"
//         },
//         "groups": {
//           "$ref": "#/definitions/simple-list-wrapper"
//         },
//         "key": {
//           "type": "string"
//         },
//         "locale": {
//           "type": "string"
//         },
//         "name": {
//           "type": "string"
//         },
//         "self": {
//           "type": "string"
//         },
//         "timeZone": {
//           "type": "string"
//         }
//       }
//     },
//     "name": {
//       "title": "name",
//       "type": "string"
//     },
//     "projectCategory": {
//       "title": "Project Category",
//       "type": "object",
//       "properties": {
//         "description": {
//           "title": "description",
//           "type": "string"
//         },
//         "id": {
//           "title": "id",
//           "type": "string"
//         },
//         "name": {
//           "title": "name",
//           "type": "string"
//         },
//         "self": {
//           "title": "self",
//           "type": "string"
//         }
//       }
//     },
//     "projectKeys": {
//       "title": "projectKeys",
//       "type": "array",
//       "items": {
//         "type": "string"
//       }
//     },
//     "projectTypeKey": {
//       "title": "projectTypeKey",
//       "type": "string"
//     },
//     "roles": {
//       "title": "roles",
//       "type": "object",
//       "patternProperties": {
//         ".+": {
//           "type": "string"
//         }
//       }
//     },
//     "self": {
//       "title": "self",
//       "type": "string"
//     },
//     "url": {
//       "title": "url",
//       "type": "string"
//     },
//     "versions": {
//       "title": "versions",
//       "type": "array",
//       "items": {
//         "title": "Version",
//         "type": "object",
//         "properties": {
//           "archived": {
//             "title": "archived",
//             "type": "boolean"
//           },
//           "description": {
//             "title": "description",
//             "type": "string"
//           },
//           "expand": {
//             "title": "expand",
//             "type": "string"
//           },
//           "id": {
//             "title": "id",
//             "type": "string"
//           },
//           "moveUnfixedIssuesTo": {
//             "title": "moveUnfixedIssuesTo",
//             "type": "string"
//           },
//           "name": {
//             "title": "name",
//             "type": "string"
//           },
//           "operations": {
//             "title": "operations",
//             "type": "array",
//             "items": {
//               "title": "Simple Link",
//               "type": "object",
//               "properties": {
//                 "href": {
//                   "title": "href",
//                   "type": "string"
//                 },
//                 "iconClass": {
//                   "title": "iconClass",
//                   "type": "string"
//                 },
//                 "id": {
//                   "title": "id",
//                   "type": "string"
//                 },
//                 "label": {
//                   "title": "label",
//                   "type": "string"
//                 },
//                 "styleClass": {
//                   "title": "styleClass",
//                   "type": "string"
//                 },
//                 "title": {
//                   "title": "title",
//                   "type": "string"
//                 },
//                 "weight": {
//                   "title": "weight",
//                   "type": "integer"
//                 }
//               }
//             }
//           },
//           "overdue": {
//             "title": "overdue",
//             "type": "boolean"
//           },
//           "project": {
//             "title": "project",
//             "type": "string"
//           },
//           "projectId": {
//             "title": "projectId",
//             "type": "integer"
//           },
//           "released": {
//             "title": "released",
//             "type": "boolean"
//           },
//           "remotelinks": {
//             "title": "remotelinks",
//             "type": "array",
//             "items": {
//               "title": "Remote Entity Link",
//               "type": "object",
//               "properties": {
//                 "link": {
//                   "title": "link"
//                 },
//                 "name": {
//                   "title": "name",
//                   "type": "string"
//                 },
//                 "self": {
//                   "title": "self",
//                   "type": "string"
//                 }
//               }
//             }
//           },
//           "self": {
//             "title": "self",
//             "type": "string"
//           },
//           "userReleaseDate": {
//             "title": "userReleaseDate",
//             "type": "string"
//           },
//           "userStartDate": {
//             "title": "userStartDate",
//             "type": "string"
//           }
//         }
//       }
//     }
//   }
// }
type Project struct {
	AssigneeType    string            `json:"assigneeType,omitempty" yaml:"assigneeType,omitempty"`
	AvatarUrls      map[string]string `json:"avatarUrls,omitempty" yaml:"avatarUrls,omitempty"`
	Components      Components        `json:"components,omitempty" yaml:"components,omitempty"`
	Description     string            `json:"description,omitempty" yaml:"description,omitempty"`
	Email           string            `json:"email,omitempty" yaml:"email,omitempty"`
	Expand          string            `json:"expand,omitempty" yaml:"expand,omitempty"`
	ID              string            `json:"id,omitempty" yaml:"id,omitempty"`
	IssueTypes      IssueTypes        `json:"issueTypes,omitempty" yaml:"issueTypes,omitempty"`
	Key             string            `json:"key,omitempty" yaml:"key,omitempty"`
	Lead            *User             `json:"lead,omitempty" yaml:"lead,omitempty"`
	Name            string            `json:"name,omitempty" yaml:"name,omitempty"`
	ProjectCategory *ProjectCategory  `json:"projectCategory,omitempty" yaml:"projectCategory,omitempty"`
	ProjectKeys     ProjectKeys       `json:"projectKeys,omitempty" yaml:"projectKeys,omitempty"`
	ProjectTypeKey  string            `json:"projectTypeKey,omitempty" yaml:"projectTypeKey,omitempty"`
	Roles           map[string]string `json:"roles,omitempty" yaml:"roles,omitempty"`
	Self            string            `json:"self,omitempty" yaml:"self,omitempty"`
	URL             string            `json:"url,omitempty" yaml:"url,omitempty"`
	Versions        Versions          `json:"versions,omitempty" yaml:"versions,omitempty"`
}
