package jiradata

/////////////////////////////////////////////////////////////////////////
// This Code is Generated by SlipScheme Project:
// https://github.com/coryb/slipscheme
//
// Generated with command:
// slipscheme -pkg jiradata -dir jiradata -overwrite schemas/IssueUpdate.json
/////////////////////////////////////////////////////////////////////////
//                            DO NOT EDIT                              //
/////////////////////////////////////////////////////////////////////////

// Properties defined from schema:
// {
//   "title": "properties",
//   "type": "array",
//   "items": {
//     "title": "Entity Property",
//     "type": "object",
//     "properties": {
//       "key": {
//         "title": "key",
//         "type": "string"
//       },
//       "value": {
//         "title": "value"
//       }
//     }
//   }
// }
type Properties []*EntityProperty
