package jiradata

/////////////////////////////////////////////////////////////////////////
// This Code is Generated by SlipScheme Project:
// https://github.com/coryb/slipscheme
//
// Generated with command:
// slipscheme -dir jiradata -pkg jiradata -overwrite schemas/PageofVersion.json
/////////////////////////////////////////////////////////////////////////
//                            DO NOT EDIT                              //
/////////////////////////////////////////////////////////////////////////

// Remotelinks defined from schema:
// {
//   "title": "remotelinks",
//   "type": "array",
//   "items": {
//     "title": "Remote Entity Link",
//     "type": "object",
//     "properties": {
//       "link": {
//         "title": "link"
//       },
//       "name": {
//         "title": "name",
//         "type": "string"
//       },
//       "self": {
//         "title": "self",
//         "type": "string"
//       }
//     }
//   }
// }
type Remotelinks []*RemoteEntityLink
