package jiradata

/////////////////////////////////////////////////////////////////////////
// This Code is Generated by SlipScheme Project:
// https://github.com/coryb/slipscheme
//
// Generated with command:
// slipscheme -dir jiradata -pkg jiradata -overwrite schemas/ListofAttachment.json
/////////////////////////////////////////////////////////////////////////
//                            DO NOT EDIT                              //
/////////////////////////////////////////////////////////////////////////

// SimpleListWrapper defined from schema:
// {
//   "title": "Simple List Wrapper",
//   "type": "object",
//   "properties": {
//     "items": {
//       "type": "array",
//       "items": {
//         "title": "Group",
//         "type": "object",
//         "properties": {
//           "name": {
//             "type": "string"
//           },
//           "self": {
//             "type": "string"
//           }
//         }
//       }
//     },
//     "max-results": {
//       "type": "integer"
//     },
//     "size": {
//       "type": "integer"
//     }
//   }
// }
type SimpleListWrapper struct {
	Items      Groups `json:"items,omitempty" yaml:"items,omitempty"`
	MaxResults int    `json:"max-results,omitempty" yaml:"max-results,omitempty"`
	Size       int    `json:"size,omitempty" yaml:"size,omitempty"`
}
