package jiradata

/////////////////////////////////////////////////////////////////////////
// This Code is Generated by SlipScheme Project:
// https://github.com/coryb/slipscheme
//
// Generated with command:
// slipscheme -dir jiradata -pkg jiradata -overwrite schemas/PageofVersion.json
/////////////////////////////////////////////////////////////////////////
//                            DO NOT EDIT                              //
/////////////////////////////////////////////////////////////////////////

// SimpleLink defined from schema:
// {
//   "title": "Simple Link",
//   "type": "object",
//   "properties": {
//     "href": {
//       "title": "href",
//       "type": "string"
//     },
//     "iconClass": {
//       "title": "iconClass",
//       "type": "string"
//     },
//     "id": {
//       "title": "id",
//       "type": "string"
//     },
//     "label": {
//       "title": "label",
//       "type": "string"
//     },
//     "styleClass": {
//       "title": "styleClass",
//       "type": "string"
//     },
//     "title": {
//       "title": "title",
//       "type": "string"
//     },
//     "weight": {
//       "title": "weight",
//       "type": "integer"
//     }
//   }
// }
type SimpleLink struct {
	Href       string `json:"href,omitempty" yaml:"href,omitempty"`
	IconClass  string `json:"iconClass,omitempty" yaml:"iconClass,omitempty"`
	ID         string `json:"id,omitempty" yaml:"id,omitempty"`
	Label      string `json:"label,omitempty" yaml:"label,omitempty"`
	StyleClass string `json:"styleClass,omitempty" yaml:"styleClass,omitempty"`
	Title      string `json:"title,omitempty" yaml:"title,omitempty"`
	Weight     int    `json:"weight,omitempty" yaml:"weight,omitempty"`
}
