package jiradata

/////////////////////////////////////////////////////////////////////////
// This Code is Generated by SlipScheme Project:
// https://github.com/coryb/slipscheme
//
// Generated with command:
// slipscheme -dir jiradata -pkg jiradata -overwrite schemas/TransitionsMeta.json
/////////////////////////////////////////////////////////////////////////
//                            DO NOT EDIT                              //
/////////////////////////////////////////////////////////////////////////

// Status defined from schema:
// {
//   "title": "Status",
//   "type": "object",
//   "properties": {
//     "description": {
//       "title": "description",
//       "type": "string"
//     },
//     "iconUrl": {
//       "title": "iconUrl",
//       "type": "string"
//     },
//     "id": {
//       "title": "id",
//       "type": "string"
//     },
//     "name": {
//       "title": "name",
//       "type": "string"
//     },
//     "self": {
//       "title": "self",
//       "type": "string"
//     },
//     "statusCategory": {
//       "title": "Status Category",
//       "type": "object",
//       "properties": {
//         "colorName": {
//           "title": "colorName",
//           "type": "string"
//         },
//         "id": {
//           "title": "id",
//           "type": "integer"
//         },
//         "key": {
//           "title": "key",
//           "type": "string"
//         },
//         "name": {
//           "title": "name",
//           "type": "string"
//         },
//         "self": {
//           "title": "self",
//           "type": "string"
//         }
//       }
//     },
//     "statusColor": {
//       "title": "statusColor",
//       "type": "string"
//     }
//   }
// }
type Status struct {
	Description    string          `json:"description,omitempty" yaml:"description,omitempty"`
	IconURL        string          `json:"iconUrl,omitempty" yaml:"iconUrl,omitempty"`
	ID             string          `json:"id,omitempty" yaml:"id,omitempty"`
	Name           string          `json:"name,omitempty" yaml:"name,omitempty"`
	Self           string          `json:"self,omitempty" yaml:"self,omitempty"`
	StatusCategory *StatusCategory `json:"statusCategory,omitempty" yaml:"statusCategory,omitempty"`
	StatusColor    string          `json:"statusColor,omitempty" yaml:"statusColor,omitempty"`
}
