package jiradata

/////////////////////////////////////////////////////////////////////////
// This Code is Generated by SlipScheme Project:
// https://github.com/coryb/slipscheme
//
// Generated with command:
// slipscheme -dir jiradata -pkg jiradata -overwrite schemas/TransitionsMeta.json
/////////////////////////////////////////////////////////////////////////
//                            DO NOT EDIT                              //
/////////////////////////////////////////////////////////////////////////

// TransitionsMeta defined from schema:
// {
//   "title": "Transitions Meta",
//   "id": "https://docs.atlassian.com/jira/REST/schema/transitions-meta#",
//   "type": "object",
//   "properties": {
//     "expand": {
//       "title": "expand",
//       "type": "string"
//     },
//     "transitions": {
//       "title": "transitions",
//       "type": "array",
//       "items": {
//         "title": "Transition",
//         "type": "object",
//         "properties": {
//           "expand": {
//             "title": "expand",
//             "type": "string"
//           },
//           "fields": {
//             "title": "fields",
//             "type": "object",
//             "patternProperties": {
//               ".+": {
//                 "title": "Field Meta",
//                 "type": "object",
//                 "properties": {
//                   "allowedValues": {
//                     "title": "allowedValues",
//                     "type": "array",
//                     "items": {}
//                   },
//                   "autoCompleteUrl": {
//                     "title": "autoCompleteUrl",
//                     "type": "string"
//                   },
//                   "defaultValue": {
//                     "title": "defaultValue"
//                   },
//                   "hasDefaultValue": {
//                     "title": "hasDefaultValue",
//                     "type": "boolean"
//                   },
//                   "key": {
//                     "title": "key",
//                     "type": "string"
//                   },
//                   "name": {
//                     "title": "name",
//                     "type": "string"
//                   },
//                   "operations": {
//                     "title": "operations",
//                     "type": "array",
//                     "items": {
//                       "type": "string"
//                     }
//                   },
//                   "required": {
//                     "title": "required",
//                     "type": "boolean"
//                   },
//                   "schema": {
//                     "title": "Json Type",
//                     "type": "object",
//                     "properties": {
//                       "custom": {
//                         "title": "custom",
//                         "type": "string"
//                       },
//                       "customId": {
//                         "title": "customId",
//                         "type": "integer"
//                       },
//                       "items": {
//                         "title": "items",
//                         "type": "string"
//                       },
//                       "system": {
//                         "title": "system",
//                         "type": "string"
//                       },
//                       "type": {
//                         "title": "type",
//                         "type": "string"
//                       }
//                     }
//                   }
//                 }
//               }
//             }
//           },
//           "hasScreen": {
//             "title": "hasScreen",
//             "type": "boolean"
//           },
//           "id": {
//             "title": "id",
//             "type": "string"
//           },
//           "name": {
//             "title": "name",
//             "type": "string"
//           },
//           "to": {
//             "title": "Status",
//             "type": "object",
//             "properties": {
//               "description": {
//                 "title": "description",
//                 "type": "string"
//               },
//               "iconUrl": {
//                 "title": "iconUrl",
//                 "type": "string"
//               },
//               "id": {
//                 "title": "id",
//                 "type": "string"
//               },
//               "name": {
//                 "title": "name",
//                 "type": "string"
//               },
//               "self": {
//                 "title": "self",
//                 "type": "string"
//               },
//               "statusCategory": {
//                 "title": "Status Category",
//                 "type": "object",
//                 "properties": {
//                   "colorName": {
//                     "title": "colorName",
//                     "type": "string"
//                   },
//                   "id": {
//                     "title": "id",
//                     "type": "integer"
//                   },
//                   "key": {
//                     "title": "key",
//                     "type": "string"
//                   },
//                   "name": {
//                     "title": "name",
//                     "type": "string"
//                   },
//                   "self": {
//                     "title": "self",
//                     "type": "string"
//                   }
//                 }
//               },
//               "statusColor": {
//                 "title": "statusColor",
//                 "type": "string"
//               }
//             }
//           }
//         }
//       }
//     }
//   }
// }
type TransitionsMeta struct {
	Expand      string      `json:"expand,omitempty" yaml:"expand,omitempty"`
	Transitions Transitions `json:"transitions,omitempty" yaml:"transitions,omitempty"`
}
