package jiradata

/////////////////////////////////////////////////////////////////////////
// This Code is Generated by SlipScheme Project:
// https://github.com/coryb/slipscheme
//
// Generated with command:
// slipscheme -dir data -pkg jiradata -overwrite schemas/SearchResults.json
/////////////////////////////////////////////////////////////////////////
//                            DO NOT EDIT                              //
/////////////////////////////////////////////////////////////////////////

// Transitions defined from schema:
// {
//   "title": "transitions",
//   "type": "array",
//   "items": {
//     "title": "Transition",
//     "type": "object",
//     "properties": {
//       "expand": {
//         "title": "expand",
//         "type": "string"
//       },
//       "fields": {
//         "title": "fields",
//         "type": "object",
//         "patternProperties": {
//           ".+": {
//             "title": "Field Meta",
//             "type": "object",
//             "properties": {
//               "allowedValues": {
//                 "type": "array",
//                 "items": {}
//               },
//               "autoCompleteUrl": {
//                 "type": "string"
//               },
//               "defaultValue": {},
//               "hasDefaultValue": {
//                 "type": "boolean"
//               },
//               "key": {
//                 "type": "string"
//               },
//               "name": {
//                 "type": "string"
//               },
//               "operations": {
//                 "type": "array",
//                 "items": {
//                   "type": "string"
//                 }
//               },
//               "required": {
//                 "type": "boolean"
//               },
//               "schema": {
//                 "$ref": "#/definitions/json-type"
//               }
//             }
//           }
//         }
//       },
//       "hasScreen": {
//         "title": "hasScreen",
//         "type": "boolean"
//       },
//       "id": {
//         "title": "id",
//         "type": "string"
//       },
//       "name": {
//         "title": "name",
//         "type": "string"
//       },
//       "to": {
//         "title": "Status",
//         "type": "object",
//         "properties": {
//           "description": {
//             "title": "description",
//             "type": "string"
//           },
//           "iconUrl": {
//             "title": "iconUrl",
//             "type": "string"
//           },
//           "id": {
//             "title": "id",
//             "type": "string"
//           },
//           "name": {
//             "title": "name",
//             "type": "string"
//           },
//           "self": {
//             "title": "self",
//             "type": "string"
//           },
//           "statusCategory": {
//             "title": "Status Category",
//             "type": "object",
//             "properties": {
//               "colorName": {
//                 "title": "colorName",
//                 "type": "string"
//               },
//               "id": {
//                 "title": "id",
//                 "type": "integer"
//               },
//               "key": {
//                 "title": "key",
//                 "type": "string"
//               },
//               "name": {
//                 "title": "name",
//                 "type": "string"
//               },
//               "self": {
//                 "title": "self",
//                 "type": "string"
//               }
//             }
//           },
//           "statusColor": {
//             "title": "statusColor",
//             "type": "string"
//           }
//         }
//       }
//     }
//   }
// }
type Transitions []*Transition
