package jiradata

/////////////////////////////////////////////////////////////////////////
// This Code is Generated by SlipScheme Project:
// https://github.com/coryb/slipscheme
//
// Generated with command:
// slipscheme -dir data -pkg jiradata -overwrite schemas/SearchResults.json
/////////////////////////////////////////////////////////////////////////
//                            DO NOT EDIT                              //
/////////////////////////////////////////////////////////////////////////

// User defined from schema:
// {
//   "title": "User",
//   "type": "object",
//   "properties": {
//     "accountId": {
//       "title": "accountId",
//       "type": "string"
//     },
//     "active": {
//       "title": "active",
//       "type": "boolean"
//     },
//     "avatarUrls": {
//       "title": "avatarUrls",
//       "type": "object",
//       "patternProperties": {
//         ".+": {
//           "type": "string"
//         }
//       }
//     },
//     "displayName": {
//       "title": "displayName",
//       "type": "string"
//     },
//     "emailAddress": {
//       "title": "emailAddress",
//       "type": "string"
//     },
//     "key": {
//       "title": "key",
//       "type": "string"
//     },
//     "name": {
//       "title": "name",
//       "type": "string"
//     },
//     "self": {
//       "title": "self",
//       "type": "string"
//     },
//     "timeZone": {
//       "title": "timeZone",
//       "type": "string"
//     }
//   }
// }
type User struct {
	AccountID    string            `json:"accountId,omitempty" yaml:"accountId,omitempty"`
	Active       bool              `json:"active,omitempty" yaml:"active,omitempty"`
	AvatarUrls   map[string]string `json:"avatarUrls,omitempty" yaml:"avatarUrls,omitempty"`
	DisplayName  string            `json:"displayName,omitempty" yaml:"displayName,omitempty"`
	EmailAddress string            `json:"emailAddress,omitempty" yaml:"emailAddress,omitempty"`
	Key          string            `json:"key,omitempty" yaml:"key,omitempty"`
	Name         string            `json:"name,omitempty" yaml:"name,omitempty"`
	Self         string            `json:"self,omitempty" yaml:"self,omitempty"`
	TimeZone     string            `json:"timeZone,omitempty" yaml:"timeZone,omitempty"`
}
