package jiradata

/////////////////////////////////////////////////////////////////////////
// This Code is Generated by SlipScheme Project:
// https://github.com/coryb/slipscheme
//
// Generated with command:
// slipscheme -dir jiradata -pkg jiradata -overwrite schemas/PageofVersion.json
/////////////////////////////////////////////////////////////////////////
//                            DO NOT EDIT                              //
/////////////////////////////////////////////////////////////////////////

// Values defined from schema:
// {
//   "title": "values",
//   "type": "array",
//   "items": {
//     "title": "Version",
//     "type": "object",
//     "properties": {
//       "archived": {
//         "title": "archived",
//         "type": "boolean"
//       },
//       "description": {
//         "title": "description",
//         "type": "string"
//       },
//       "expand": {
//         "title": "expand",
//         "type": "string"
//       },
//       "id": {
//         "title": "id",
//         "type": "string"
//       },
//       "moveUnfixedIssuesTo": {
//         "title": "moveUnfixedIssuesTo",
//         "type": "string"
//       },
//       "name": {
//         "title": "name",
//         "type": "string"
//       },
//       "operations": {
//         "title": "operations",
//         "type": "array",
//         "items": {
//           "title": "Simple Link",
//           "type": "object",
//           "properties": {
//             "href": {
//               "title": "href",
//               "type": "string"
//             },
//             "iconClass": {
//               "title": "iconClass",
//               "type": "string"
//             },
//             "id": {
//               "title": "id",
//               "type": "string"
//             },
//             "label": {
//               "title": "label",
//               "type": "string"
//             },
//             "styleClass": {
//               "title": "styleClass",
//               "type": "string"
//             },
//             "title": {
//               "title": "title",
//               "type": "string"
//             },
//             "weight": {
//               "title": "weight",
//               "type": "integer"
//             }
//           }
//         }
//       },
//       "overdue": {
//         "title": "overdue",
//         "type": "boolean"
//       },
//       "project": {
//         "title": "project",
//         "type": "string"
//       },
//       "projectId": {
//         "title": "projectId",
//         "type": "integer"
//       },
//       "released": {
//         "title": "released",
//         "type": "boolean"
//       },
//       "remotelinks": {
//         "title": "remotelinks",
//         "type": "array",
//         "items": {
//           "title": "Remote Entity Link",
//           "type": "object",
//           "properties": {
//             "link": {
//               "title": "link"
//             },
//             "name": {
//               "title": "name",
//               "type": "string"
//             },
//             "self": {
//               "title": "self",
//               "type": "string"
//             }
//           }
//         }
//       },
//       "self": {
//         "title": "self",
//         "type": "string"
//       },
//       "userReleaseDate": {
//         "title": "userReleaseDate",
//         "type": "string"
//       },
//       "userStartDate": {
//         "title": "userStartDate",
//         "type": "string"
//       }
//     }
//   }
// }
type Values []*Version
