package jiradata

/////////////////////////////////////////////////////////////////////////
// This Code is Generated by SlipScheme Project:
// https://github.com/coryb/slipscheme
//
// Generated with command:
// slipscheme -dir jiradata -pkg jiradata -overwrite schemas/WorklogWithPagination.json
/////////////////////////////////////////////////////////////////////////
//                            DO NOT EDIT                              //
/////////////////////////////////////////////////////////////////////////

// Visibility defined from schema:
// {
//   "title": "Visibility",
//   "type": "object",
//   "properties": {
//     "type": {
//       "title": "type",
//       "type": "string"
//     },
//     "value": {
//       "title": "value",
//       "type": "string"
//     }
//   }
// }
type Visibility struct {
	Type  string `json:"type,omitempty" yaml:"type,omitempty"`
	Value string `json:"value,omitempty" yaml:"value,omitempty"`
}
