package jiradata

/////////////////////////////////////////////////////////////////////////
// This Code is Generated by SlipScheme Project:
// https://github.com/coryb/slipscheme
//
// Generated with command:
// slipscheme -dir jiradata -pkg jiradata -overwrite schemas/WorklogWithPagination.json
/////////////////////////////////////////////////////////////////////////
//                            DO NOT EDIT                              //
/////////////////////////////////////////////////////////////////////////

// WorklogWithPagination defined from schema:
// {
//   "title": "Worklog With Pagination",
//   "id": "https://docs.atlassian.com/jira/REST/schema/worklog-with-pagination#",
//   "type": "object",
//   "definitions": {
//     "user": {
//       "title": "User",
//       "type": "object",
//       "properties": {
//         "accountId": {
//           "type": "string"
//         },
//         "active": {
//           "type": "boolean"
//         },
//         "avatarUrls": {
//           "type": "object",
//           "patternProperties": {
//             ".+": {
//               "type": "string"
//             }
//           }
//         },
//         "displayName": {
//           "type": "string"
//         },
//         "emailAddress": {
//           "type": "string"
//         },
//         "key": {
//           "type": "string"
//         },
//         "name": {
//           "type": "string"
//         },
//         "self": {
//           "type": "string"
//         },
//         "timeZone": {
//           "type": "string"
//         }
//       }
//     }
//   },
//   "properties": {
//     "maxResults": {
//       "title": "maxResults",
//       "type": "integer"
//     },
//     "startAt": {
//       "title": "startAt",
//       "type": "integer"
//     },
//     "total": {
//       "title": "total",
//       "type": "integer"
//     },
//     "worklogs": {
//       "title": "worklogs",
//       "type": "array",
//       "items": {
//         "title": "Worklog",
//         "type": "object",
//         "properties": {
//           "author": {
//             "title": "User",
//             "type": "object",
//             "properties": {
//               "accountId": {
//                 "type": "string"
//               },
//               "active": {
//                 "type": "boolean"
//               },
//               "avatarUrls": {
//                 "type": "object",
//                 "patternProperties": {
//                   ".+": {
//                     "type": "string"
//                   }
//                 }
//               },
//               "displayName": {
//                 "type": "string"
//               },
//               "emailAddress": {
//                 "type": "string"
//               },
//               "key": {
//                 "type": "string"
//               },
//               "name": {
//                 "type": "string"
//               },
//               "self": {
//                 "type": "string"
//               },
//               "timeZone": {
//                 "type": "string"
//               }
//             }
//           },
//           "comment": {
//             "title": "comment",
//             "type": "string"
//           },
//           "created": {
//             "title": "created",
//             "type": "string"
//           },
//           "id": {
//             "title": "id",
//             "type": "string"
//           },
//           "issueId": {
//             "title": "issueId",
//             "type": "string"
//           },
//           "properties": {
//             "title": "properties",
//             "type": "array",
//             "items": {
//               "title": "Entity Property",
//               "type": "object",
//               "properties": {
//                 "key": {
//                   "title": "key",
//                   "type": "string"
//                 },
//                 "value": {
//                   "title": "value"
//                 }
//               }
//             }
//           },
//           "self": {
//             "title": "self",
//             "type": "string"
//           },
//           "started": {
//             "title": "started",
//             "type": "string"
//           },
//           "timeSpent": {
//             "title": "timeSpent",
//             "type": "string"
//           },
//           "timeSpentSeconds": {
//             "title": "timeSpentSeconds",
//             "type": "integer"
//           },
//           "updateAuthor": {
//             "title": "User",
//             "type": "object",
//             "properties": {
//               "accountId": {
//                 "type": "string"
//               },
//               "active": {
//                 "type": "boolean"
//               },
//               "avatarUrls": {
//                 "type": "object",
//                 "patternProperties": {
//                   ".+": {
//                     "type": "string"
//                   }
//                 }
//               },
//               "displayName": {
//                 "type": "string"
//               },
//               "emailAddress": {
//                 "type": "string"
//               },
//               "key": {
//                 "type": "string"
//               },
//               "name": {
//                 "type": "string"
//               },
//               "self": {
//                 "type": "string"
//               },
//               "timeZone": {
//                 "type": "string"
//               }
//             }
//           },
//           "updated": {
//             "title": "updated",
//             "type": "string"
//           },
//           "visibility": {
//             "title": "Visibility",
//             "type": "object",
//             "properties": {
//               "type": {
//                 "title": "type",
//                 "type": "string"
//               },
//               "value": {
//                 "title": "value",
//                 "type": "string"
//               }
//             }
//           }
//         }
//       }
//     }
//   }
// }
type WorklogWithPagination struct {
	MaxResults int      `json:"maxResults,omitempty" yaml:"maxResults,omitempty"`
	StartAt    int      `json:"startAt,omitempty" yaml:"startAt,omitempty"`
	Total      int      `json:"total,omitempty" yaml:"total,omitempty"`
	Worklogs   Worklogs `json:"worklogs,omitempty" yaml:"worklogs,omitempty"`
}
