package jiradata

/////////////////////////////////////////////////////////////////////////
// This Code is Generated by SlipScheme Project:
// https://github.com/coryb/slipscheme
//
// Generated with command:
// slipscheme -dir jiradata -pkg jiradata -overwrite schemas/WorklogWithPagination.json
/////////////////////////////////////////////////////////////////////////
//                            DO NOT EDIT                              //
/////////////////////////////////////////////////////////////////////////

// Worklog defined from schema:
// {
//   "title": "Worklog",
//   "type": "object",
//   "properties": {
//     "author": {
//       "title": "User",
//       "type": "object",
//       "properties": {
//         "accountId": {
//           "type": "string"
//         },
//         "active": {
//           "type": "boolean"
//         },
//         "avatarUrls": {
//           "type": "object",
//           "patternProperties": {
//             ".+": {
//               "type": "string"
//             }
//           }
//         },
//         "displayName": {
//           "type": "string"
//         },
//         "emailAddress": {
//           "type": "string"
//         },
//         "key": {
//           "type": "string"
//         },
//         "name": {
//           "type": "string"
//         },
//         "self": {
//           "type": "string"
//         },
//         "timeZone": {
//           "type": "string"
//         }
//       }
//     },
//     "comment": {
//       "title": "comment",
//       "type": "string"
//     },
//     "created": {
//       "title": "created",
//       "type": "string"
//     },
//     "id": {
//       "title": "id",
//       "type": "string"
//     },
//     "issueId": {
//       "title": "issueId",
//       "type": "string"
//     },
//     "properties": {
//       "title": "properties",
//       "type": "array",
//       "items": {
//         "title": "Entity Property",
//         "type": "object",
//         "properties": {
//           "key": {
//             "title": "key",
//             "type": "string"
//           },
//           "value": {
//             "title": "value"
//           }
//         }
//       }
//     },
//     "self": {
//       "title": "self",
//       "type": "string"
//     },
//     "started": {
//       "title": "started",
//       "type": "string"
//     },
//     "timeSpent": {
//       "title": "timeSpent",
//       "type": "string"
//     },
//     "timeSpentSeconds": {
//       "title": "timeSpentSeconds",
//       "type": "integer"
//     },
//     "updateAuthor": {
//       "title": "User",
//       "type": "object",
//       "properties": {
//         "accountId": {
//           "type": "string"
//         },
//         "active": {
//           "type": "boolean"
//         },
//         "avatarUrls": {
//           "type": "object",
//           "patternProperties": {
//             ".+": {
//               "type": "string"
//             }
//           }
//         },
//         "displayName": {
//           "type": "string"
//         },
//         "emailAddress": {
//           "type": "string"
//         },
//         "key": {
//           "type": "string"
//         },
//         "name": {
//           "type": "string"
//         },
//         "self": {
//           "type": "string"
//         },
//         "timeZone": {
//           "type": "string"
//         }
//       }
//     },
//     "updated": {
//       "title": "updated",
//       "type": "string"
//     },
//     "visibility": {
//       "title": "Visibility",
//       "type": "object",
//       "properties": {
//         "type": {
//           "title": "type",
//           "type": "string"
//         },
//         "value": {
//           "title": "value",
//           "type": "string"
//         }
//       }
//     }
//   }
// }
type Worklog struct {
	Author           *User       `json:"author,omitempty" yaml:"author,omitempty"`
	Comment          string      `json:"comment,omitempty" yaml:"comment,omitempty"`
	Created          string      `json:"created,omitempty" yaml:"created,omitempty"`
	ID               string      `json:"id,omitempty" yaml:"id,omitempty"`
	IssueID          string      `json:"issueId,omitempty" yaml:"issueId,omitempty"`
	Properties       Properties  `json:"properties,omitempty" yaml:"properties,omitempty"`
	Self             string      `json:"self,omitempty" yaml:"self,omitempty"`
	Started          string      `json:"started,omitempty" yaml:"started,omitempty"`
	TimeSpent        string      `json:"timeSpent,omitempty" yaml:"timeSpent,omitempty"`
	TimeSpentSeconds int         `json:"timeSpentSeconds,omitempty" yaml:"timeSpentSeconds,omitempty"`
	UpdateAuthor     *User       `json:"updateAuthor,omitempty" yaml:"updateAuthor,omitempty"`
	Updated          string      `json:"updated,omitempty" yaml:"updated,omitempty"`
	Visibility       *Visibility `json:"visibility,omitempty" yaml:"visibility,omitempty"`
}
